# New Version Test

## Fix 0 — Convert Two-Component System to a Vivarium `PartitionedProcess`

### Changes to the Two-Component System process

Fix 0 migrated the Two-Component System from the original standalone process implementation to a Vivarium `PartitionedProcess` interface so that it can operate within the current simulation framework.

The main changes were:

* Change `TwoComponentSystem` to inherit from `PartitionedProcess`.
* Register the process name and default topology using `topology_registry`, with ports for:

  * `bulk`
  * `listeners`
  * `timestep`
* Replace the original process execution interface with the `PartitionedProcess` methods:

  * `ports_schema()` to define the process ports and defaults.
  * `calculate_request()` to calculate the molecules required for the next timestep.
  * `evolve_state()` to apply the calculated molecule-count changes.
* Build molecule indices from the `bulk` store dynamically using `bulk_name_to_idx()` and obtain molecule counts using the shared `counts()` helper.
* Preserve the existing two-component-system ODE calculation while adapting it to the new process interface.
* Maintain a process-local NumPy random state using the configured seed for stochastic handling when molecule allocations need to be adjusted.
* Continue using the BDF ODE solver for the normal simulation calculation, including the existing handling of negative molecule counts and fallback behaviour.
* Preserve the existing stoichiometric/dependency-matrix calculations and the conversion between independent molecule changes and the full set of molecule-count updates.

The new process interface separates **request calculation** from **state evolution**: `calculate_request()` determines the bulk molecules needed and stores the expected changes, while `evolve_state()` applies those changes and re-solves the system if the requested molecules were not fully allocated.

### Result

Fix 0 therefore primarily changed the **process integration/interface**, rather than changing the underlying Two-Component System reaction model. The existing ODE, stoichiometry, dependency mapping, molecule-allocation, and negative-count handling logic were retained while the process was adapted to the `PartitionedProcess` execution model.

## test 2 - use the old configuration and found that the TU list is not matched

```bash 
(vecoli) katha@IT106990:~/dev/vEcoli-colony-sim$ python ecoli/experiments/ecoli_engine_process.py --config configs/colony_baseline_test2.json
/home/katha/dev/vEcoli-colony-sim/.venv/lib/python3.12/site-packages/vivarium/core/serialize.py:286: UserWarning: Searched through serializers to find <vivarium.core.serialize.NumpyFallbackSerializer object at 0x7fa41580a090> for data of type <class 'ecoli.library.schema.MetadataArray'>. This is inefficient.
  warnings.warn(
Traceback (most recent call last):
  File "/home/katha/dev/vEcoli-colony-sim/ecoli/experiments/ecoli_engine_process.py", line 553, in <module>
    run_simulation(config)
  File "/home/katha/dev/vEcoli-colony-sim/ecoli/experiments/ecoli_engine_process.py", line 418, in run_simulation
    agent_composite = agent_composer.generate(agent_config, path=agent_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katha/dev/vEcoli-colony-sim/.venv/lib/python3.12/site-packages/vivarium/core/composer.py", line 409, in generate
    processes = self.generate_processes(config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katha/dev/vEcoli-colony-sim/ecoli/experiments/ecoli_engine_process.py", line 217, in generate_processes
    cell_process = EngineProcess(cell_process_config)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katha/dev/vEcoli-colony-sim/ecoli/processes/engine_process.py", line 306, in __init__
    self.sim = Engine(
               ^^^^^^^
  File "/home/katha/dev/vEcoli-colony-sim/.venv/lib/python3.12/site-packages/vivarium/core/engine.py", line 468, in __init__
    self.run_steps()
  File "/home/katha/dev/vEcoli-colony-sim/.venv/lib/python3.12/site-packages/vivarium/core/engine.py", line 833, in run_steps
    update, store = self._calculate_update(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katha/dev/vEcoli-colony-sim/.venv/lib/python3.12/site-packages/vivarium/core/engine.py", line 719, in _calculate_update
    return _process_update(
           ^^^^^^^^^^^^^^^^
  File "/home/katha/dev/vEcoli-colony-sim/.venv/lib/python3.12/site-packages/vivarium/core/engine.py", line 1159, in _process_update
    process = _invoke_process(
              ^^^^^^^^^^^^^^^^
  File "/home/katha/dev/vEcoli-colony-sim/.venv/lib/python3.12/site-packages/vivarium/core/engine.py", line 1129, in _invoke_process
    process.send_command('next_update', (interval, states))
  File "/home/katha/dev/vEcoli-colony-sim/.venv/lib/python3.12/site-packages/vivarium/core/process.py", line 275, in send_command
    self._command_result = self.run_command_method(
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katha/dev/vEcoli-colony-sim/.venv/lib/python3.12/site-packages/vivarium/core/process.py", line 302, in run_command_method
    return getattr(self, command)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katha/dev/vEcoli-colony-sim/ecoli/processes/listeners/mass_listener.py", line 232, in next_update
    self.bulk_idx = bulk_name_to_idx(self.bulk_ids, bulk_ids)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katha/dev/vEcoli-colony-sim/ecoli/library/schema.py", line 343, in bulk_name_to_idx
    raise ValueError(f"Names not found in bulk_names: {missing.tolist()}")
def agent_dirs(history_root):
    return sorted(
        [
            path
            for path in history_root.glob("experiment_id=*__inner/variant=0/lineage_seed=0/generation=*/agent_id=*")
            if path.is_dir()
        ],
        key=lambda path: (
            int(next(part.split("=", 1)[1] for part in path.parts if part.startswith("generation="))),
            next(part.split("=", 1)[1] for part in path.parts if part.startswith("agent_id=")),
        ),
    )

def snapshot_files(history_root):
    return sorted(history_root.rglob("*.pq"), key=lambda path: int(path.stem))

def summarize_run(name, history_root):
    dirs = agent_dirs(history_root)
    files = snapshot_files(history_root)
    stems = sorted({int(path.stem) for path in files})
    print(f\
)
    print(f\
    print(f\
    print(f\
    print(f\
    sample_path = files[-1]
    sample_frame = pd.read_parquet(sample_path, columns=[column for column in ["time", "boundary__length", "boundary__mass", "boundary__width"] if column in pd.read_parquet(sample_path, nrows=0).columns])
    print(f\
    display(sample_frame.head(3).round(4))
    return stems

left_times = summarize_run("baseline_test1", RUNS["baseline_test1"])
right_times = summarize_run("baseline_test3", RUNS["baseline_test3"])
common_times = sorted(set(left_times) & set(right_times))

print(\
)
print(\
print(\
print(\
Exception: ('cell_process',) is not a valid path from ('agents', 'outer')
```

## test 1 - start with empty simdata

```bash 
(vecoli) katha@IT106990:~/dev/vEcoli-colony-sim$ python ecoli/experiments/ecoli_engine_process.py --config configs/colony_baseline_test2.json
```
Results: export error of system final status

## Fix 1 - format the out path of colony final state

### Changes to `ecoli/experiments/ecoli_engine_process.py`

In `colony_save_states()`:

* Detect the parquet emitter and account for the `agents/outer` wrapper.
* Use the correct internal path:

  * Parquet: `agents/outer/agents/<agent_id>/cell_process`
  * Other emitters: `agents/<agent_id>/cell_process`
* Extract `state_to_save["agents"]["outer"]` before saving so that colony JSON files retain the expected `agents/<agent_id>/...` structure.
* Continue extracting each `EngineProcess` inner state with `get_inner_state`.
* Preserve `bulk_dtypes` and `unique_dtypes` metadata.

### Output files

The simulation produces two types of output:

* **Transient simulation state:** emitted continuously using the configured Parquet emitter and saved under the customised `out_dir`, e.g.:

  ```text
  out/colony_runs/baseline_test1/
  ```

* **Final colony state:** saved explicitly by `colony_save_states()` as a JSON file under `/data`, e.g.:

  ```text
  data/baseline_test1_seed_0_colony_t6000.json
  ```

The final JSON is intended to provide a restorable colony state, while the Parquet output captures the transient simulation data.

The fix was verified with a 1-second smoke test. The resulting JSON successfully loads and contains the expected:

```text
agents/
└── 0/
    ├── bulk
    ├── unique
    ├── bulk_dtypes
    └── unique_dtypes
```

rather than the incorrect `agents/outer/...` structure.

## Smoke test

```bash
(vecoli) katha@IT106990:~/dev/vEcoli-colony-sim$ python ecoli/experiments/ecoli_engine_process.py --config /tmp/colony_smoke_test.json

Simulation ID: 2026-08-25_13-13-11_409544+0000
Created: 08/25/2026 at 14:13:16
Description: Test: 2 generations (4 cells), save parquet per cell, save final state
Progress:|██████████████████████████████████████████████████| 0.0/1.0 simulated seconds remaining    
Completed in 2.12 seconds
/home/katha/dev/vEcoli-colony-sim/.venv/lib/python3.12/site-packages/vivarium/core/serialize.py:286: UserWarning: Searched through serializers to find <vivarium.core.serialize.NumpyFallbackSerializer object at 0x7f51683e4560> for data of type <class 'ecoli.library.schema.MetadataArray'>. This is inefficient.
  warnings.warn(
Finished saving the state at t = 1
```

configuration in smoke test:
```text
    ...
   "max_duration": 1,
    "save": true,
    "save_times": [1],
    ...
```

**Notes about the warning**:

The warning says that this works, but Vivarium had to search through the available serializers to find the appropriate fallback.

So:
```text
MetadataArray
    ↓
Vivarium serializer lookup
    ↓
NumpyFallbackSerializer
    ↓
JSON serialization succeeds
```

This is primarily a performance/implementation warning, not a correctness problem.

## test 3 - run with customised emit step

Planned steps:
1. check all file related to the early PR (#390) - all cahnges added (ecoli_engine_process.py, serialize.py)
2. change if needed - skipped
3. set a short test (use colony_baseline_test3.json) and run the simulation
```bash
python ecoli/experiments/ecoli_engine_process.py --config configs/colony_baseline_test3.json
```
4. check results
the file names still the same with test 1, need further checks whether the emit steps are different
    - time step still 1 second.
    - however, no data saved under the subfolder without __inner suffix in test3; there is in test1.

In [ ]:
# Read data format from test1 and test3
import json
from pathlib import Path

PROJECTS = {
    "baseline_test1": Path("/home/katha/dev/vEcoli-colony-sim/out/colony_runs/baseline_test1"),
    "baseline_test3": Path("/home/katha/dev/vEcoli-colony-sim/out/colony_runs/baseline_test3"),
}
FALLBACK_JSON = {
    "baseline_test1": Path("/home/katha/dev/vEcoli-colony-sim/data/baseline_2gen_seed_0_colony_t6000.json"),
    "baseline_test3": Path("/home/katha/dev/vEcoli-colony-sim/data/baseline_test3_seed_10_colony_t6000.json"),
}

def find_json_path(project_name, project_dir):
    json_files = sorted(project_dir.rglob("*.json"))
    if json_files:
        return json_files[-1]

    fallback = FALLBACK_JSON[project_name]
    if fallback.exists():
        print(f"Using fallback JSON for {project_name}: {fallback}")
        return fallback

    raise FileNotFoundError(f"No JSON result found for {project_name} in {project_dir}")

def load_project(project_name, project_dir):
    json_path = find_json_path(project_name, project_dir)
    with open(json_path, "r") as f:
        data = json.load(f)

    agents = data["agents"]
    agent_ids = sorted(agents.keys())
    all_keys = sorted({key for agent in agents.values() for key in agent.keys()})
    return {
        "name": project_name,
        "path": json_path,
        "data": data,
        "agents": agents,
        "agent_ids": agent_ids,
        "all_keys": all_keys,
    }

def print_project_summary(project):
    print(f"\n=== {project['name']} ===")
    print(f"JSON path: {project['path']}")
    print(f"Agent count: {len(project['agent_ids'])}")
    print("Agent IDs:")
    print(project['agent_ids'])
    print("Unique categories (keys):")
    print(project['all_keys'])

    sample_agent = project['agents'][project['agent_ids'][0]]
    print(f"\n--- Data preview for agent '{project['agent_ids'][0]}' ---")
    for key in project['all_keys']:
        value = sample_agent.get(key, None)
        print(f"\nCategory: '{key}'")
        print(f"Type: {type(value)}")
        if isinstance(value, dict):
            print(f"Exclusive subcategories: {sorted(value.keys())}")
        elif isinstance(value, list):
            print(f"Length: {len(value)}")
            print(f"First 3 entries: {value[:3]}")
        else:
            print(f"Value: {value}")

    exchange_keys = set()
    media_ids = set()
    for agent in project['agents'].values():
        env = agent.get('environment', {})
        exchange = env.get('exchange', {})
        exchange_keys.update(exchange.keys())
        media_ids.add(env.get('media_id', None))

    print("\nExclusive list of all exchange chemicals across agents:")
    print(sorted(exchange_keys))
    print("\nExclusive list of all media_id values across agents:")
    print(sorted(media_ids))
    return exchange_keys, media_ids

projects = [load_project(name, path) for name, path in PROJECTS.items()]
project_summaries = {project['name']: print_project_summary(project) for project in projects}

left, right = projects
left_keys = set(left['all_keys'])
right_keys = set(right['all_keys'])
common_keys = sorted(left_keys & right_keys)

print("\n=== Comparison ===")
print("Keys only in baseline_test1:")
print(sorted(left_keys - right_keys))
print("Keys only in baseline_test3:")
print(sorted(right_keys - left_keys))
print("Shared keys:")
print(common_keys)

test1_exchange, test1_media = project_summaries["baseline_test1"]
test3_exchange, test3_media = project_summaries["baseline_test3"]

print("\n=== Environment comparison ===")
print("Exchange chemicals only in baseline_test1:")
print(sorted(test1_exchange - test3_exchange))
print("Exchange chemicals only in baseline_test3:")
print(sorted(test3_exchange - test1_exchange))
print("Media IDs only in baseline_test1:")
print(sorted(test1_media - test3_media))
print("Media IDs only in baseline_test3:")
print(sorted(test3_media - test1_media))

sample_left = left['agents'][left['agent_ids'][0]]
sample_right = right['agents'][right['agent_ids'][0]]
list_diffs = []
for key in common_keys:
    left_value = sample_left.get(key)
    right_value = sample_right.get(key)
    if isinstance(left_value, list) and isinstance(right_value, list):
        left_len = len(left_value)
        right_len = len(right_value)
        if left_len != right_len:
            list_diffs.append((key, left_len, right_len))

print("\n=== First-agent value differences ===")
print("global_time:", sample_left.get("global_time"), sample_right.get("global_time"))
print("timestep:", sample_left.get("timestep"), sample_right.get("timestep"))
print("list-length differences:")
print(list_diffs)

Using fallback JSON for baseline_test1: /home/katha/dev/vEcoli-colony-sim/data/baseline_2gen_seed_0_colony_t6000.json
Using fallback JSON for baseline_test3: /home/katha/dev/vEcoli-colony-sim/data/baseline_test3_seed_10_colony_t6000.json

=== baseline_test1 ===
JSON path: /home/katha/dev/vEcoli-colony-sim/data/baseline_2gen_seed_0_colony_t6000.json
Agent count: 4
Agent IDs:
['000', '001', '010', '011']
Unique categories (keys):
['allocate', 'allocator_rng', 'boundary', 'bulk', 'bulk_dtypes', 'cytoplasm', 'divide', 'division_threshold', 'division_trigger', 'environment', 'global_time', 'listeners', 'next_update_time', 'periplasm', 'process_state', 'request', 'timeline', 'timestep', 'unique', 'unique_dtypes']

--- Data preview for agent '000' ---

Category: 'allocate'
Type: <class 'dict'>
Exclusive subcategories: ['ecoli-chromosome-replication', 'ecoli-complexation', 'ecoli-equilibrium', 'ecoli-polypeptide-elongation', 'ecoli-polypeptide-initiation', 'ecoli-protein-degradation', 'ecoli-rna-degradation', 'ecoli-rna-maturation', 'ecoli-transcript-elongation', 'ecoli-transcript-initiation', 'ecoli-two-component-system']

Category: 'allocator_rng'
Type: <class 'str'>
Value: !RandomStateSerializer[('MT19937', [1032081874, 3921390043, 1775671866, 3050400842, 613040236, 3120117409, 313685, 4009028496, 3451362311, 1611313565, 1216908950, 1280315550, 2094310855, 486956331, 2341192965, 835091154, 3469137642, 701790974, 3147330632, 4284971845, 196483250, 3605856335, 2998782482, 1551059047, 772023894, 3028362759, 2054139155, 1697376821, 3256171168, 1295408492, 409809183, 2117531738, 1695919879, 3445769087, 3326475278, 232416836, 3552623864, 3205095980, 1077074508, 4278080904, 2968265471, 3704500986, 3882900839, 789273759, 1080402407, 1090975211, 3535748992, 2131110366, 2733628459, 4136815966, 2975648483, 441807864, 3935205644, 1818741280, 3271911483, 1332745807, 3611986686, 1572158218, 912666257, 2536700016, 3509520182, 1088173350, 1466161057, 1311289951, 638889302, 474310959, 16099021, 3804857380, 1649083047, 109896131, 1790668085, 1439623627, 843405050, 3384613611, 1733936594, 1041102730, 4055991230, 1191452382, 624854345, 2549983004, 4015258918, 3869158634, 3984714047, 3937804543, 1214635968, 2671153274, 2535405486, 1775239987, 1059390738, 1959764595, 3170376020, 1288373577, 1994694084, 2902699030, 1578473538, 450227662, 2068582566, 1115484484, 3444317595, 2852521307, 4272668033, 1757042351, 3500757260, 2056716882, 1108825639, 4082717543, 1201302238, 3812000102, 4119009861, 1169347595, 927793760, 2554810447, 3963020241, 1683047499, 664898468, 401792039, 3820141271, 122366489, 3437100371, 1297400071, 2900778454, 2145745181, 1662829702, 3543582910, 3744815117, 3968678915, 2362748030, 1738172779, 473649490, 3005872091, 2015423007, 286813273, 1393385633, 291291045, 1437198751, 3311450589, 1605575454, 2840687300, 251149992, 1477484755, 2724058470, 1274262785, 1443064206, 4190055674, 508362701, 2749407602, 2283053506, 653496659, 3022176595, 543268490, 2451662600, 2425880969, 328793967, 1813524068, 1998674803, 1916212885, 2564627712, 1188070503, 770233052, 1236725099, 807363954, 2815101083, 2732803583, 2315911796, 2860392242, 3703766677, 2974201812, 404885013, 4253797361, 2213148963, 4253610927, 2334338951, 569568549, 2109955398, 2884619441, 1192005198, 4165299419, 881560041, 2033851039, 1316818697, 2912564956, 759592011, 1662321997, 2352268211, 2472668813, 1748411940, 2205964883, 278657968, 688618796, 1404628761, 2844929334, 1296607811, 3767959242, 1756927758, 2400428205, 746917070, 100289546, 2595707575, 13936431, 2275876178, 2161008984, 3841692491, 1611310130, 2541163498, 3875144532, 3083723040, 832767288, 2544109543, 1865657129, 336785305, 652241199, 589080414, 1802589930, 2410155660, 3942235356, 2561924050, 1112017384, 1159240390, 2633666653, 213306710, 3176925642, 2600723653, 1936245345, 1761218751, 3671083478, 2894274282, 4087175786, 391503184, 4118815092, 2344018904, 839749608, 3501518703, 1198998148, 4064898146, 3298733103, 3253828167, 3331301824, 3834719708, 871133417, 1729379804, 1830989345, 3770536849, 2719718284, 3825556985, 3745439382, 2868809406, 3891588386, 4268701692, 47288211, 864571640, 518302418, 3546269653, 1704287850, 3160572980, 1897467980, 4139230304, 3760314127, 2059617469, 536263470, 751138857, 3965016625, 2052020415, 1291694588, 3192037080, 121722634, 1839313403, 517997228, 2994936551, 4016122469, 2714784075, 1471095771, 1161744401, 1603315552, 2639000406, 3413833014, 623844348, 4118013824, 1983148740, 4085233103, 1916855955, 3036486322, 3589519497, 447719820, 1004392791, 3236702063, 574118585, 802671899, 1554276294, 378292643, 3224783216, 1759413889, 591761827, 3839340915, 3508400725, 1876599572, 1947964784, 1408397245, 982889045, 4124170675, 2098860955, 3506251502, 4197462446, 3612618607, 3716907723, 75473432, 2730609833, 2846507945, 202389162, 2790034502, 421510153, 3580166595, 1258910199, 2389744966, 1936945421, 2069825270, 3958960046, 3677693309, 460995059, 1507911965, 37745995, 1989012183, 1820601775, 878322920, 3349723339, 2112614444, 2128140294, 4082760457, 1058956857, 54646469, 2152475138, 2256966474, 2128716979, 1762082182, 4068050576, 1694221389, 24452939, 3221322983, 648563525, 2073075851, 3250532805, 2793118322, 1299832709, 2521748586, 731739743, 3390147539, 2943253097, 3540422801, 1358114037, 1034637728, 3198539133, 1629959033, 1464502199, 3506565678, 463053346, 3796839116, 651013134, 4237975786, 958656082, 3790924224, 3742275158, 3347566065, 526959587, 2489238777, 2276133746, 2678748316, 251302339, 1093787229, 1294989243, 1570064338, 3390718640, 552803601, 300913192, 668209980, 194688033, 928365435, 3129265150, 2339526628, 2758853943, 4202310755, 3935495003, 2131086132, 561744486, 597176764, 701316267, 538801143, 3463377140, 2608480757, 3326752502, 3479424301, 1064276651, 3811533309, 3541342397, 2718954110, 1785923701, 3121900366, 1452147335, 3205150314, 4155482261, 1632936636, 3768998688, 3931943263, 3137353437, 2022440589, 2152225487, 1287555445, 4041691225, 4290305816, 1360165438, 3413046131, 2333932745, 4081410225, 3623643605, 2014529802, 1426044404, 3069569095, 1043632600, 3383895000, 1198873096, 1085954095, 334981577, 4172828401, 60074271, 2885767649, 2458700598, 2830565676, 4028045007, 3286445094, 2890086724, 152440906, 242354399, 198564009, 1425010012, 2721737825, 4290953152, 2731148449, 983830786, 1055050110, 3619679851, 975616190, 3746992813, 3697868382, 1444356458, 1710191601, 3356766059, 3912064452, 3397812288, 2810804013, 3226283594, 1010259341, 829962082, 3049213292, 2599119913, 888254907, 4220859276, 3613253681, 1851930497, 2700306248, 3444857851, 1263010466, 323438362, 2850158862, 3552751497, 3230014784, 3412551742, 742377185, 4072595862, 4078616219, 2410974155, 4018714913, 334642751, 3382396849, 2977926417, 693556567, 1355725868, 2776585371, 1269908280, 2625112153, 2521891012, 885605884, 3284171339, 4099459144, 138685048, 2263284538, 1410995963, 1030544518, 228636867, 3030270421, 1955400378, 2776649903, 663186218, 3068969852, 1618579617, 2461774092, 355424883, 2956672077, 885920794, 2730875442, 1361233633, 2403752018, 1446226307, 581334078, 361958507, 2945854253, 2779001474, 2588831352, 1466360347, 2974621756, 1130424433, 212837932, 476978521, 2123708187, 1158785345, 1414203456, 248253606, 1775228288, 986203880, 793650060, 2209215553, 4247665525, 155819413, 980609745, 649559934, 504478912, 2218932683, 4287389529, 2229193359, 2888196271, 362527568, 3168712864, 421235707, 1571065625, 203968139, 666657259, 1327916748, 314918391, 403098506, 3865127306, 3528373798, 2945100723, 3580786672, 510353403, 4204213028, 2719485825, 2220899278, 1821099420, 1127284242, 2966514337, 2200260466, 558582100, 3728598089, 1134341464, 3473147716, 4218216491, 1996610033, 653028826, 3674669869, 2830754130, 4095325885, 941803812, 1935253859, 996679642, 1457459, 535523921, 3829953832, 796344107, 1762062636, 3137945079, 3397423328, 1819780807, 3940467799, 2940234590, 1566742919, 1454983706, 3397366244, 2347159905, 903059790, 2460498950, 949605333, 1306563147, 535384949, 418024557, 749387334, 3139078628, 3532554245, 1558559398, 639042860, 218994854, 2711097801, 1125231203, 3939806455, 555930258, 258684905, 1234682429, 3749036029, 2502274952, 127212997, 3072732685, 1193227584, 2744569339, 3968370324, 3288656619, 1140774881, 2620526010, 1763632115, 1422553814, 2738184240, 2917644312, 2661781153, 3991241647, 3635937597, 703901144, 1601777819, 3523778854, 1130117886, 535740417, 167332812, 2071926244, 4045288130, 425349519, 3845174998, 1508057461, 3719252273, 1555146024, 1939348636], 624, 0, 0.0)]

Category: 'boundary'
Type: <class 'dict'>
Exclusive subcategories: ['angle', 'external', 'inner_surface_area', 'length', 'location', 'mass', 'mmol_to_counts', 'outer_surface_area', 'thrust', 'torque', 'volume', 'width']

Category: 'bulk'
Type: <class 'list'>
Length: 16321
First 3 entries: [['--TRANS-ACENAPHTHENE-12-DIOL[c]', 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.09208979698442e-07, 0.0, 0.0], ['1-6-Galactofuran[c]', 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.8111332289748734e-06, 0.0, 0.0], ['1-ACYLGLYCEROL-3-P-ACYLTRANSFER-MONOMER[i]', 87, 0.0, 0.0, 0.0, 0.0, 0.0, 4.5607055853672875e-05, 0.0, 0.0, 0.0]]

Category: 'bulk_dtypes'
Type: <class 'str'>
Value: [('id', '<U50'), ('count', '<i8'), ('rRNA_submass', '<f8'), ('tRNA_submass', '<f8'), ('mRNA_submass', '<f8'), ('miscRNA_submass', '<f8'), ('nonspecific_RNA_submass', '<f8'), ('protein_submass', '<f8'), ('metabolite_submass', '<f8'), ('water_submass', '<f8'), ('DNA_submass', '<f8')]

Category: 'cytoplasm'
Type: <class 'dict'>
Exclusive subcategories: ['global']

Category: 'divide'
Type: <class 'bool'>
Value: False

Category: 'division_threshold'
Type: <class 'bool'>
Value: True

Category: 'division_trigger'
Type: <class 'bool'>
Value: False

Category: 'environment'
Type: <class 'dict'>
Exclusive subcategories: ['exchange', 'media_id']

Category: 'global_time'
Type: <class 'float'>
Value: 6000.0

Category: 'listeners'
Type: <class 'dict'>
Exclusive subcategories: ['atp', 'complexation_listener', 'dna_supercoiling', 'enzyme_kinetics', 'equilibrium_listener', 'fba_results', 'growth_limits', 'mass', 'monomer_counts', 'replication_data', 'ribosome_data', 'rna_counts', 'rna_degradation_listener', 'rna_maturation_listener', 'rna_synth_prob', 'rnap_data', 'transcript_elongation_listener', 'unique_molecule_counts']

Category: 'next_update_time'
Type: <class 'dict'>
Exclusive subcategories: ['chromosome_structure', 'ecoli-chromosome-replication', 'ecoli-complexation', 'ecoli-equilibrium', 'ecoli-polypeptide-elongation', 'ecoli-polypeptide-initiation', 'ecoli-protein-degradation', 'ecoli-rna-degradation', 'ecoli-rna-maturation', 'ecoli-transcript-elongation', 'ecoli-transcript-initiation', 'ecoli-two-component-system', 'metabolism', 'ribosome_data_listener', 'rnap_data_listener', 'tf_binding', 'tf_unbinding']

Category: 'periplasm'
Type: <class 'dict'>
Exclusive subcategories: ['global']

Category: 'process_state'
Type: <class 'dict'>
Exclusive subcategories: ['polypeptide_elongation']

Category: 'request'
Type: <class 'dict'>
Exclusive subcategories: ['ecoli-chromosome-replication', 'ecoli-complexation', 'ecoli-equilibrium', 'ecoli-polypeptide-elongation', 'ecoli-polypeptide-initiation', 'ecoli-protein-degradation', 'ecoli-rna-degradation', 'ecoli-rna-maturation', 'ecoli-transcript-elongation', 'ecoli-transcript-initiation', 'ecoli-two-component-system']

Category: 'timeline'
Type: <class 'dict'>
Exclusive subcategories: ['time']

Category: 'timestep'
Type: <class 'float'>
Value: 1.0

Category: 'unique'
Type: <class 'dict'>
Exclusive subcategories: ['DnaA_box', 'RNA', 'active_RNAP', 'active_replisome', 'active_ribosome', 'chromosomal_segment', 'chromosome_domain', 'full_chromosome', 'gene', 'oriC', 'promoter']

Category: 'unique_dtypes'
Type: <class 'dict'>
Exclusive subcategories: ['DnaA_box', 'RNA', 'active_RNAP', 'active_replisome', 'active_ribosome', 'chromosomal_segment', 'chromosome_domain', 'full_chromosome', 'gene', 'oriC', 'promoter']

Exclusive list of all exchange chemicals across agents:
['4FE-4S', '5-Deoxy-D-Ribofuranose', 'ACET', 'AMMONIUM', 'ARABINOSE', 'ARG', 'ASN', 'BETAINE', 'BUTANAL', 'CA+2', 'CARBON-DIOXIDE', 'CARBON-MONOXIDE', 'CH33ADO', 'CL-', 'CO+2', 'CPD-10774', 'CPD-108', 'CPD-1772', 'CPD-183', 'CPD-239', 'CPD-520', 'CPD-534', 'CPD-560', 'CPD-564', 'CPD0-1958', 'CYS', 'CYTIDINE', 'CYTOSINE', 'D-ALANINE', 'D-LACTATE', 'ETOH', 'FE+2', 'FE+3', 'FORMATE', 'FUM', 'GLC', 'GLC-D-LACTONE', 'GLN', 'GLT', 'GLY', 'GLYCEROL', 'GLYCOLALDEHYDE', 'GLYCOLLATE', 'HIS', 'HYDROGEN-MOLECULE', 'HYPOXANTHINE', 'ILE', 'IMIDAZOLE-PYRUVATE', 'INDOLE', 'K+', 'L-ALPHA-ALANINE', 'L-ASPARTATE', 'L-SELENOCYSTEINE', 'LEU', 'LYS', 'MAL', 'MET', 'METOH', 'MG+2', 'MI-PENTAKISPHOSPHATE', 'MN+2', 'NA+', 'NI+2', 'NITRATE', 'NITRITE', 'OXYGEN-MOLECULE', 'PHE', 'PRO', 'PROTON', 'Pi', 'S-ADENOSYL-4-METHYLTHIO-2-OXOBUTANOATE', 'S-ADENOSYLMETHIONINE', 'SER', 'SUC', 'SULFATE', 'THR', 'THYMINE', 'TRP', 'TUNGSTATE', 'TYR', 'UNDECAPRENYL-DIPHOSPHATE', 'URACIL', 'UREA', 'VAL', 'WATER', 'XANTHINE', 'ZN+2']

Exclusive list of all media_id values across agents:
['minimal']

=== baseline_test3 ===
JSON path: /home/katha/dev/vEcoli-colony-sim/data/baseline_test3_seed_10_colony_t6000.json
Agent count: 4
Agent IDs:
['000', '001', '010', '011']
Unique categories (keys):
['allocate', 'allocator_rng', 'boundary', 'bulk', 'bulk_dtypes', 'cytoplasm', 'divide', 'division_threshold', 'division_trigger', 'environment', 'global_time', 'listeners', 'next_update_time', 'periplasm', 'process_state', 'request', 'timeline', 'timestep', 'unique', 'unique_dtypes']

--- Data preview for agent '000' ---

Category: 'allocate'
Type: <class 'dict'>
Exclusive subcategories: ['ecoli-chromosome-replication', 'ecoli-complexation', 'ecoli-equilibrium', 'ecoli-polypeptide-elongation', 'ecoli-polypeptide-initiation', 'ecoli-protein-degradation', 'ecoli-rna-degradation', 'ecoli-rna-maturation', 'ecoli-transcript-elongation', 'ecoli-transcript-initiation', 'ecoli-two-component-system']

Category: 'allocator_rng'
Type: <class 'str'>

In [ ]:
# Read data sample from test1 and test3
from pathlib import Path
import pandas as pd
import pyarrow.parquet as pq

RUNS = {
    "baseline_test1": Path("/home/katha/dev/vEcoli-colony-sim/out/colony_runs/baseline_test1/2026-08-23_20-47-32_975315%2B0000__inner/history"),
    "baseline_test3": Path("/home/katha/dev/vEcoli-colony-sim/out/colony_runs/baseline_test3/2026-08-25_15-22-46_783084%2B0000__inner/history"),
}


def agent_dirs(history_root):
    return sorted(
        [
            path
            for path in history_root.glob("experiment_id=*__inner/variant=0/lineage_seed=0/generation=*/agent_id=*")
            if path.is_dir()
        ],
        key=lambda path: (
            int(next(part.split("=", 1)[1] for part in path.parts if part.startswith("generation="))),
            next(part.split("=", 1)[1] for part in path.parts if part.startswith("agent_id=")),
        ),
    )


def snapshot_files(history_root):
    return sorted(history_root.rglob("*.pq"), key=lambda path: int(path.stem))


def summarize_run(name, history_root):
    dirs = agent_dirs(history_root)
    files = snapshot_files(history_root)
    stems = sorted({int(path.stem) for path in files})

    print(f"\n=== {name} ===")
    print(f"History root: {history_root}")
    print(f"Agent dirs: {len(dirs)}")
    print(f"Parquet snapshots: {len(files)}")
    print(f"Snapshot times: {stems}")

    sample_path = files[-1]
    sample_schema = pq.ParquetFile(sample_path).schema_arrow.names
    sample_columns = [column for column in ["time", "boundary__length", "boundary__mass", "boundary__width"] if column in sample_schema]
    sample_frame = pd.read_parquet(sample_path, columns=sample_columns) if sample_columns else pd.read_parquet(sample_path).head(3)

    print(f"Sample parquet: {sample_path}")
    display(sample_frame.head(3).round(4))
    return stems


left_times = summarize_run("baseline_test1", RUNS["baseline_test1"])
right_times = summarize_run("baseline_test3", RUNS["baseline_test3"])
common_times = sorted(set(left_times) & set(right_times))

print("\n=== Snapshot comparison ===")
print("Only in baseline_test1:", sorted(set(left_times) - set(right_times)))
print("Only in baseline_test3:", sorted(set(right_times) - set(left_times)))
print("Common snapshot times:", common_times)

=== baseline_test1 ===
History root: /home/katha/dev/vEcoli-colony-sim/out/colony_runs/baseline_test1/2026-08-23_20-47-32_975315%2B0000__inner/history
Agent dirs: 7
Parquet snapshots: 29
Snapshot times: [400, 800, 1200, 1600, 2000, 2400, 2529, 2660]
Sample parquet: /home/katha/dev/vEcoli-colony-sim/out/colony_runs/baseline_test1/2026-08-23_20-47-32_975315%2B0000__inner/history/experiment_id=2026-08-23_20-47-32_975315%2B0000__inner/variant=0/lineage_seed=0/generation=2/agent_id=01/2660.pq

,time,boundary__length,boundary__mass,boundary__width
0,4929.0,!units[2.9386553972661176 micrometer],!units[2250.836680478823 femtogram],!units[1.0 micrometer]
1,4930.0,!units[2.9393422699621565 micrometer],!units[2251.4300958881754 femtogram],!units[1.0 micrometer]
2,4931.0,!units[2.940037815687907 micrometer],!units[2252.031004257295 femtogram],!units[1.0 micrometer]

=== baseline_test3 ===
History root: /home/katha/dev/vEcoli-colony-sim/out/colony_runs/baseline_test3/2026-08-25_15-22-46_783084%2B0000__inner/history
Agent dirs: 7
Parquet snapshots: 27
Snapshot times: [400, 800, 1200, 1600, 2000, 2400, 2671, 2800, 2836]
Sample parquet: /home/katha/dev/vEcoli-colony-sim/out/colony_runs/baseline_test3/2026-08-25_15-22-46_783084%2B0000__inner/history/experiment_id=2026-08-25_15-22-46_783084%2B0000__inner/variant=0/lineage_seed=0/generation=2/agent_id=01/2836.pq

,time,boundary__length,boundary__mass,boundary__width
0,5471.0,!units[2.902185899379881 micrometer],!units[2219.329296152958 femtogram],!units[1.0 micrometer]
1,5472.0,!units[2.9027037435469425 micrometer],!units[2219.7766813964677 femtogram],!units[1.0 micrometer]
2,5473.0,!units[2.903230100953602 micrometer],!units[2220.231421550997 femtogram],!units[1.0 micrometer]

=== Snapshot comparison ===
Only in baseline_test1: [2529, 2660]
Only in baseline_test3: [2671, 2800, 2836]
Common snapshot times: [400, 800, 1200, 1600, 2000, 2400]

In [ ]:
from pathlib import Path
import pandas as pd
import pyarrow.parquet as pq

RUNS = {
    "baseline_test1": Path("/home/katha/dev/vEcoli-colony-sim/out/colony_runs/baseline_test1/2026-08-23_20-47-32_975315%2B0000__inner/history"),
    "baseline_test3": Path("/home/katha/dev/vEcoli-colony-sim/out/colony_runs/baseline_test3/2026-08-25_15-22-46_783084%2B0000__inner/history"),
}


def sample_parquet_path(history_root):
    files = sorted(history_root.rglob("*.pq"), key=lambda path: int(path.stem))
    if not files:
        raise FileNotFoundError(f"No .pq files found under {history_root}")
    return files[-1]


for name, history_root in RUNS.items():
    sample_path = sample_parquet_path(history_root)
    parquet_file = pq.ParquetFile(sample_path)
    schema = parquet_file.schema_arrow
    df = pd.read_parquet(sample_path)

    print(f"\n=== {name} ===")
    print(f"Sample pq file: {sample_path}")
    print("Schema:")
    print(schema)
    print("\nColumns and dtypes:")
    print(df.dtypes)
    print("\nFirst 3 rows:")
    display(df.head(3))

=== baseline_test1 ===
Sample pq file: /home/katha/dev/vEcoli-colony-sim/out/colony_runs/baseline_test1/2026-08-23_20-47-32_975315%2B0000__inner/history/experiment_id=2026-08-23_20-47-32_975315%2B0000__inner/variant=0/lineage_seed=0/generation=2/agent_id=01/2660.pq
Schema:
bulk: large_list<element: int64>
  child 0, element: int64
environment__exchange__4FE-4S: int64
environment__exchange__5-Deoxy-D-Ribofuranose: int64
environment__exchange__ACET: int64
environment__exchange__AMMONIUM: int64
environment__exchange__ARABINOSE: int64
environment__exchange__ARG: int64
environment__exchange__ASN: int64
environment__exchange__BETAINE: int64
environment__exchange__BUTANAL: int64
environment__exchange__CA+2: int64
environment__exchange__CARBON-DIOXIDE: int64
environment__exchange__CARBON-MONOXIDE: int64
environment__exchange__CH33ADO: int64
environment__exchange__CL-: int64
environment__exchange__CO+2: int64
environment__exchange__CPD-10774: int64
environment__exchange__CPD-108: int64
environment__exchange__CPD-1772: int64
environment__exchange__CPD-183: int64
environment__exchange__CPD-239: int64
environment__exchange__CPD-520: int64
environment__exchange__CPD-534: int64
environment__exchange__CPD-560: int64
environment__exchange__CPD-564: int64
environment__exchange__CPD0-1958: int64
environment__exchange__CYS: int64
environment__exchange__CYTIDINE: int64
environment__exchange__CYTOSINE: int64
environment__exchange__D-ALANINE: int64
environment__exchange__D-LACTATE: int64
environment__exchange__ETOH: int64
environment__exchange__FE+2: int64
environment__exchange__FE+3: int64
environment__exchange__FORMATE: int64
environment__exchange__FUM: int64
environment__exchange__GLC: int64
environment__exchange__GLC-D-LACTONE: int64
environment__exchange__GLN: int64
environment__exchange__GLT: int64
environment__exchange__GLY: int64
environment__exchange__GLYCEROL: int64
environment__exchange__GLYCOLALDEHYDE: int64
environment__exchange__GLYCOLLATE: int64
environment__exchange__HIS: int64
environment__exchange__HYDROGEN-MOLECULE: int64
environment__exchange__HYPOXANTHINE: int64
environment__exchange__ILE: int64
environment__exchange__IMIDAZOLE-PYRUVATE: int64
environment__exchange__INDOLE: int64
environment__exchange__K+: int64
environment__exchange__L-ALPHA-ALANINE: int64
environment__exchange__L-ASPARTATE: int64
environment__exchange__L-SELENOCYSTEINE: int64
environment__exchange__LEU: int64
environment__exchange__LYS: int64
environment__exchange__MAL: int64
environment__exchange__MET: int64
environment__exchange__METOH: int64
environment__exchange__MG+2: int64
environment__exchange__MI-PENTAKISPHOSPHATE: int64
environment__exchange__MN+2: int64
environment__exchange__NA+: int64
environment__exchange__NI+2: int64
environment__exchange__NITRATE: int64
environment__exchange__NITRITE: int64
environment__exchange__OXYGEN-MOLECULE: int64
environment__exchange__PHE: int64
environment__exchange__PRO: int64
environment__exchange__PROTON: int64
environment__exchange__Pi: int64
environment__exchange__S-ADENOSYL-4-METHYLTHIO-2-OXOBUTANOATE: int64
environment__exchange__S-ADENOSYLMETHIONINE: int64
environment__exchange__SER: int64
environment__exchange__SUC: int64
environment__exchange__SULFATE: int64
environment__exchange__THR: int64
environment__exchange__THYMINE: int64
environment__exchange__TRP: int64
environment__exchange__TUNGSTATE: int64
environment__exchange__TYR: int64
environment__exchange__UNDECAPRENYL-DIPHOSPHATE: int64
environment__exchange__URACIL: int64
environment__exchange__UREA: int64
environment__exchange__VAL: int64
environment__exchange__WATER: int64
environment__exchange__XANTHINE: int64
environment__exchange__ZN+2: int64
listeners__rna_counts__mRNA_counts: large_list<element: uint32>
  child 0, element: uint32
listeners__rna_counts__full_mRNA_counts: large_list<element: uint32>
  child 0, element: uint32
listeners__rna_counts__partial_mRNA_counts: large_list<element: uint32>
  child 0, element: uint32
listeners__rna_counts__mRNA_cistron_counts: large_list<element: uint32>
  child 0, element: uint32
listeners__rna_counts__full_mRNA_cistron_counts: large_list<element: uint32>
  child 0, element: uint32
listeners__rna_counts__partial_mRNA_cistron_counts: large_list<element: uint32>
  child 0, element: uint32
listeners__rna_counts__partial_rRNA_counts: large_list<element: int64>
  child 0, element: int64
listeners__rna_counts__partial_rRNA_cistron_counts: large_list<element: int64>
  child 0, element: int64
listeners__dna_supercoiling__segment_left_boundary_coordinates: large_list<element: null>
  child 0, element: null
listeners__dna_supercoiling__segment_right_boundary_coordinates: large_list<element: null>
  child 0, element: null
listeners__dna_supercoiling__segment_domain_indexes: large_list<element: null>
  child 0, element: null
listeners__dna_supercoiling__segment_superhelical_densities: large_list<element: null>
  child 0, element: null
listeners__mass__cell_mass: double
listeners__mass__water_mass: double
listeners__mass__dry_mass: double
listeners__mass__rna_mass: double
listeners__mass__rRna_mass: double
listeners__mass__tRna_mass: double
listeners__mass__mRna_mass: double
listeners__mass__dna_mass: double
listeners__mass__protein_mass: double
listeners__mass__smallMolecule_mass: double
listeners__mass__volume: double
listeners__mass__protein_mass_fraction: double
listeners__mass__rna_mass_fraction: double
listeners__mass__growth: double
listeners__mass__instantaneous_growth_rate: double
listeners__mass__dry_mass_fold_change: double
listeners__mass__protein_mass_fold_change: double
listeners__mass__rna_mass_fold_change: double
listeners__mass__small_molecule_fold_change: double
listeners__mass__projection_mass: double
listeners__mass__cytosol_mass: double
listeners__mass__extracellular_mass: double
listeners__mass__flagellum_mass: double
listeners__mass__membrane_mass: double
listeners__mass__outer_membrane_mass: double
listeners__mass__periplasm_mass: double
listeners__mass__pilus_mass: double
listeners__mass__inner_membrane_mass: double
listeners__mass__expected_mass_fold_change: double
listeners__replication_data__critical_initiation_mass: double
listeners__replication_data__critical_mass_per_oriC: double
listeners__replication_data__fork_coordinates: large_list<element: int64>
  child 0, element: int64
listeners__replication_data__fork_domains: large_list<element: int32>
  child 0, element: int32
listeners__replication_data__fork_unique_index: large_list<element: int64>
  child 0, element: int64
listeners__replication_data__number_of_oric: int64
listeners__replication_data__free_DnaA_boxes: int64
listeners__replication_data__total_DnaA_boxes: int64
listeners__rnap_data__n_total_collisions: int64
listeners__rnap_data__n_headon_collisions: int64
listeners__rnap_data__n_codirectional_collisions: int64
listeners__rnap_data__headon_collision_coordinates: large_list<element: int64>
  child 0, element: int64
listeners__rnap_data__codirectional_collision_coordinates: large_list<element: int64>
  child 0, element: int64
listeners__rnap_data__n_removed_ribosomes: int64
listeners__rnap_data__incomplete_transcription_events: large_list<element: int64>
  child 0, element: int64
listeners__rnap_data__n_empty_fork_collisions: int64
listeners__rnap_data__empty_fork_collision_coordinates: large_list<element: null>
  child 0, element: null
listeners__rnap_data__actual_elongations: int64
listeners__rnap_data__did_terminate: int64
listeners__rnap_data__termination_loss: int64
listeners__rnap_data__did_stall: int64
listeners__rnap_data__did_initialize: int64
listeners__rnap_data__rna_init_event: large_list<element: uint16>
  child 0, element: uint16
listeners__rnap_data__active_rnap_coordinates: large_list<element: int64>
  child 0, element: int64
listeners__rnap_data__active_rnap_domain_indexes: large_list<element: uint16>
  child 0, element: uint16
listeners__rnap_data__active_rnap_unique_indexes: large_list<element: int64>
  child 0, element: int64
listeners__rnap_data__active_rnap_on_stable_RNA_indexes: large_list<element: int64>
  child 0, element: int64
listeners__rnap_data__active_rnap_n_bound_ribosomes: large_list<element: uint16>
  child 0, element: uint16
listeners__rnap_data__rna_init_event_per_cistron: large_list<element: uint16>
  child 0, element: uint16
listeners__complexation_listener__complexation_events: large_list<element: uint16>
  child 0, element: uint16
listeners__equilibrium_listener__reaction_rates: large_list<element: double>
  child 0, element: double
listeners__fba_results__media_id: large_string
listeners__fba_results__conc_updates: large_list<element: double>
  child 0, element: double
listeners__fba_results__catalyst_counts: large_list<element: uint32>
  child 0, element: uint32
listeners__fba_results__translation_gtp: double
listeners__fba_results__coefficient: double
listeners__fba_results__unconstrained_molecules: large_list<element: bool>
  child 0, element: bool
listeners__fba_results__constrained_molecules: large_list<element: bool>
  child 0, element: bool
listeners__fba_results__uptake_constraints: large_list<element: double>
  child 0, element: double
listeners__fba_results__delta_metabolites: large_list<element: int64>
  child 0, element: int64
listeners__fba_results__reaction_fluxes: large_list<element: double>
  child 0, element: double
listeners__fba_results__external_exchange_fluxes: large_list<element: double>
  child 0, element: double
listeners__fba_results__objective_value: double
listeners__fba_results__shadow_prices: large_list<element: double>
  child 0, element: double
listeners__fba_results__reduced_costs: large_list<element: double>
  child 0, element: double
listeners__fba_results__target_concentrations: large_list<element: double>
  child 0, element: double
listeners__fba_results__homeostatic_objective_values: large_list<element: double>
  child 0, element: double
listeners__fba_results__kinetic_objective_values: large_list<element: double>
  child 0, element: double
listeners__fba_results__base_reaction_fluxes: large_list<element: double>
  child 0, element: double
listeners__fba_results__estimated_homeostatic_dmdt: large_list<element: int64>
  child 0, element: int64
listeners__fba_results__target_homeostatic_dmdt: large_list<element: int64>
  child 0, element: int64
listeners__fba_results__homeostatic_metabolite_counts: large_list<element: int64>
  child 0, element: int64
listeners__enzyme_kinetics__metabolite_counts_init: large_list<element: int64>
  child 0, element: int64
listeners__enzyme_kinetics__metabolite_counts_final: large_list<element: int64>
  child 0, element: int64
listeners__enzyme_kinetics__enzyme_counts_init: large_list<element: int64>
  child 0, element: int64
listeners__enzyme_kinetics__counts_to_molar: double
listeners__enzyme_kinetics__actual_fluxes: large_list<element: double>
  child 0, element: double
listeners__enzyme_kinetics__target_fluxes: large_list<element: double>
  child 0, element: double
listeners__enzyme_kinetics__target_fluxes_upper: large_list<element: double>
  child 0, element: double
listeners__enzyme_kinetics__target_fluxes_lower: large_list<element: double>
  child 0, element: double
listeners__enzyme_kinetics__target_aa_conc: large_list<element: double>
  child 0, element: double
listeners__growth_limits__fraction_trna_charged: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_allocated: large_list<element: int64>
  child 0, element: int64
listeners__growth_limits__aa_pool_size: large_list<element: int64>
  child 0, element: int64
listeners__growth_limits__aa_request_size: large_list<element: double>
  child 0, element: double
listeners__growth_limits__active_ribosome_allocated: int64
listeners__growth_limits__net_charged: large_list<element: int64>
  child 0, element: int64
listeners__growth_limits__aas_used: large_list<element: int64>
  child 0, element: int64
listeners__growth_limits__aa_count_diff: large_list<element: double>
  child 0, element: double
listeners__growth_limits__original_aa_supply: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_in_media: large_list<element: bool>
  child 0, element: bool
listeners__growth_limits__synthetase_conc: large_list<element: double>
  child 0, element: double
listeners__growth_limits__uncharged_trna_conc: large_list<element: double>
  child 0, element: double
listeners__growth_limits__charged_trna_conc: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_conc: large_list<element: double>
  child 0, element: double
listeners__growth_limits__ribosome_conc: double
listeners__growth_limits__fraction_aa_to_elongate: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_supply: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_synthesis: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_import: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_export: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_importers: large_list<element: int64>
  child 0, element: int64
listeners__growth_limits__aa_exporters: large_list<element: int64>
  child 0, element: int64
listeners__growth_limits__aa_supply_enzymes_fwd: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_supply_enzymes_rev: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_supply_aa_conc: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_supply_fraction_fwd: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_supply_fraction_rev: large_list<element: double>
  child 0, element: double
listeners__growth_limits__ppgpp_conc: double
listeners__growth_limits__rela_conc: double
listeners__growth_limits__spot_conc: double
listeners__growth_limits__rela_syn: large_list<element: double>
  child 0, element: double
listeners__growth_limits__spot_syn: double
listeners__growth_limits__spot_deg: double
listeners__growth_limits__spot_deg_inhibited: large_list<element: double>
  child 0, element: double
listeners__growth_limits__trna_charged: large_list<element: int64>
  child 0, element: int64
listeners__growth_limits__ntp_used: large_list<element: int64>
  child 0, element: int64
listeners__growth_limits__ntp_pool_size: large_list<element: int64>
  child 0, element: int64
listeners__growth_limits__ntp_request_size: large_list<element: int64>
  child 0, element: int64
listeners__growth_limits__ntp_allocated: large_list<element: int64>
  child 0, element: int64
listeners__ribosome_data__translation_supply: large_list<element: double>
  child 0, element: double
listeners__ribosome_data__effective_elongation_rate: double
listeners__ribosome_data__aa_count_in_sequence: large_list<element: int64>
  child 0, element: int64
listeners__ribosome_data__aa_counts: large_list<element: double>
  child 0, element: double
listeners__ribosome_data__actual_elongations: int64
listeners__ribosome_data__actual_elongation_hist: large_list<element: int64>
  child 0, element: int64
listeners__ribosome_data__elongations_non_terminating_hist: large_list<element: int64>
  child 0, element: int64
listeners__ribosome_data__did_terminate: int64
listeners__ribosome_data__termination_loss: int64
listeners__ribosome_data__num_trpA_terminated: int64
listeners__ribosome_data__process_elongation_rate: double
listeners__ribosome_data__did_initialize: int64
listeners__ribosome_data__target_prob_translation_per_transcript: large_list<element: double>
  child 0, element: double
listeners__ribosome_data__actual_prob_translation_per_transcript: large_list<element: double>
  child 0, element: double
listeners__ribosome_data__mRNA_is_overcrowded: large_list<element: bool>
  child 0, element: bool
listeners__ribosome_data__ribosome_init_event_per_monomer: large_list<element: uint32>
  child 0, element: uint32
listeners__ribosome_data__max_p: double
listeners__ribosome_data__max_p_per_protein: large_list<element: double>
  child 0, element: double
listeners__ribosome_data__rRNA_initiated_TU: large_list<element: int64>
  child 0, element: int64
listeners__ribosome_data__rRNA_init_prob_TU: large_list<element: double>
  child 0, element: double
listeners__ribosome_data__total_rna_init: int64
listeners__ribosome_data__n_ribosomes_per_transcript: large_list<element: uint32>
  child 0, element: uint32
listeners__ribosome_data__n_ribosomes_on_partial_mRNA_per_transcript: large_list<element: uint32>
  child 0, element: uint32
listeners__ribosome_data__total_rRNA_initiated: int64
listeners__ribosome_data__total_rRNA_init_prob: double
listeners__ribosome_data__rRNA5S_initiated: int64
listeners__ribosome_data__rRNA16S_initiated: int64
listeners__ribosome_data__rRNA23S_initiated: int64
listeners__ribosome_data__rRNA5S_init_prob: double
listeners__ribosome_data__rRNA16S_init_prob: double
listeners__ribosome_data__rRNA23S_init_prob: double
listeners__ribosome_data__mRNA_TU_index: large_list<element: uint16>
  child 0, element: uint16
listeners__ribosome_data__n_ribosomes_on_each_mRNA: large_list<element: uint16>
  child 0, element: uint16
listeners__ribosome_data__protein_mass_on_polysomes: large_list<element: double>
  child 0, element: double
listeners__rna_degradation_listener__fraction_active_endornases: double
listeners__rna_degradation_listener__diff_relative_first_order_decay: double
listeners__rna_degradation_listener__fract_endo_rrna_counts: double
listeners__rna_degradation_listener__count_rna_degraded: large_list<element: uint16>
  child 0, element: uint16
listeners__rna_degradation_listener__count_RNA_degraded_per_cistron: large_list<element: uint16>
  child 0, element: uint16
listeners__rna_degradation_listener__nucleotides_from_degradation: int64
listeners__rna_degradation_listener__fragment_bases_digested: int64
listeners__rna_maturation_listener__total_maturation_events: int64
listeners__rna_maturation_listener__total_degraded_ntps: int64
listeners__rna_maturation_listener__unprocessed_rnas_consumed: large_list<element: int64>
  child 0, element: int64
listeners__rna_maturation_listener__mature_rnas_generated: large_list<element: int64>
  child 0, element: int64
listeners__rna_maturation_listener__maturation_enzyme_counts: large_list<element: int64>
  child 0, element: int64
listeners__rna_synth_prob__p_promoter_bound: large_list<element: double>
  child 0, element: double
listeners__rna_synth_prob__n_promoter_bound: large_list<element: int64>
  child 0, element: int64
listeners__rna_synth_prob__n_actual_bound: large_list<element: int64>
  child 0, element: int64
listeners__rna_synth_prob__n_available_promoters: large_list<element: int64>
  child 0, element: int64
listeners__rna_synth_prob__n_bound_TF_per_TU: large_list<element: large_list<element: uint16>>
  child 0, element: large_list<element: uint16>
      child 0, element: uint16
listeners__rna_synth_prob__target_rna_synth_prob: large_list<element: double>
  child 0, element: double
listeners__rna_synth_prob__actual_rna_synth_prob: large_list<element: double>
  child 0, element: double
listeners__rna_synth_prob__tu_is_overcrowded: large_list<element: bool>
  child 0, element: bool
listeners__rna_synth_prob__total_rna_init: int64
listeners__rna_synth_prob__max_p: double
listeners__rna_synth_prob__promoter_copy_number: large_list<element: uint16>
  child 0, element: uint16
listeners__rna_synth_prob__gene_copy_number: large_list<element: uint16>
  child 0, element: uint16
listeners__rna_synth_prob__bound_TF_indexes: large_list<element: uint16>
  child 0, element: uint16
listeners__rna_synth_prob__bound_TF_coordinates: large_list<element: int64>
  child 0, element: int64
listeners__rna_synth_prob__bound_TF_domains: large_list<element: uint16>
  child 0, element: uint16

,bulk,environment__exchange__4FE-4S,environment__exchange__5-Deoxy-D-Ribofuranose,environment__exchange__ACET,environment__exchange__AMMONIUM,environment__exchange__ARABINOSE,environment__exchange__ARG,environment__exchange__ASN,environment__exchange__BETAINE,environment__exchange__BUTANAL,...,boundary__length,boundary__outer_surface_area,boundary__inner_surface_area,boundary__mmol_to_counts,boundary__mass,boundary__location,boundary__angle,boundary__thrust,boundary__torque,time
0,"[0, 0, 203, 0, 0, 0, 0, 0, 0, 0, 0, 107, 1, 0,...",0,462494,0,-3620566979,0,0,0,0,0,...,!units[2.9386553972661176 micrometer],!units[9.232058207483231 micrometer ** 2],!units[7.955946585038178 micrometer ** 2],!units[1232259.5743286018 / millimolar],!units[2250.836680478823 femtogram],"[!units[25.68031388583054 micrometer], !units[...",2.192812,0.0,0.0,4929.0
1,"[0, 0, 203, 0, 0, 0, 0, 0, 0, 0, 0, 107, 1, 0,...",0,462614,0,-3621568326,0,0,0,0,0,...,!units[2.9393422699621565 micrometer],!units[9.234216081699056 micrometer ** 2],!units[7.957806184665098 micrometer ** 2],!units[1232584.449885354 / millimolar],!units[2251.4300958881754 femtogram],"[!units[25.67990380604872 micrometer], !units[...",2.196973,0.0,0.0,4930.0
2,"[0, 0, 203, 0, 0, 0, 0, 0, 0, 0, 0, 107, 1, 0,...",0,462756,0,-3622559563,0,0,0,0,0,...,!units[2.940037815687907 micrometer],!units[9.23640120304131 micrometer ** 2],!units[7.95968926515377 micrometer ** 2],!units[1232913.4275928722 / millimolar],!units[2252.031004257295 femtogram],"[!units[25.679053877746526 micrometer], !units...",2.200529,0.0,0.0,4931.0

=== baseline_test3 ===
Sample pq file: /home/katha/dev/vEcoli-colony-sim/out/colony_runs/baseline_test3/2026-08-25_15-22-46_783084%2B0000__inner/history/experiment_id=2026-08-25_15-22-46_783084%2B0000__inner/variant=0/lineage_seed=0/generation=2/agent_id=01/2836.pq
Schema:
bulk: large_list<element: int64>
  child 0, element: int64
environment__exchange__4FE-4S: int64
environment__exchange__5-Deoxy-D-Ribofuranose: int64
environment__exchange__ACET: int64
environment__exchange__AMMONIUM: int64
environment__exchange__ARABINOSE: int64
environment__exchange__ARG: int64
environment__exchange__ASN: int64
environment__exchange__BETAINE: int64
environment__exchange__BUTANAL: int64
environment__exchange__CA+2: int64
environment__exchange__CARBON-DIOXIDE: int64
environment__exchange__CARBON-MONOXIDE: int64
environment__exchange__CH33ADO: int64
environment__exchange__CL-: int64
environment__exchange__CO+2: int64
environment__exchange__CPD-10774: int64
environment__exchange__CPD-108: int64
environment__exchange__CPD-1772: int64
environment__exchange__CPD-183: int64
environment__exchange__CPD-239: int64
environment__exchange__CPD-520: int64
environment__exchange__CPD-534: int64
environment__exchange__CPD-560: int64
environment__exchange__CPD-564: int64
environment__exchange__CPD0-1958: int64
environment__exchange__CYS: int64
environment__exchange__CYTIDINE: int64
environment__exchange__CYTOSINE: int64
environment__exchange__D-ALANINE: int64
environment__exchange__D-LACTATE: int64
environment__exchange__ETOH: int64
environment__exchange__FE+2: int64
environment__exchange__FE+3: int64
environment__exchange__FORMATE: int64
environment__exchange__FUM: int64
environment__exchange__GLC: int64
environment__exchange__GLC-D-LACTONE: int64
environment__exchange__GLN: int64
environment__exchange__GLT: int64
environment__exchange__GLY: int64
environment__exchange__GLYCEROL: int64
environment__exchange__GLYCOLALDEHYDE: int64
environment__exchange__GLYCOLLATE: int64
environment__exchange__HIS: int64
environment__exchange__HYDROGEN-MOLECULE: int64
environment__exchange__HYPOXANTHINE: int64
environment__exchange__ILE: int64
environment__exchange__IMIDAZOLE-PYRUVATE: int64
environment__exchange__INDOLE: int64
environment__exchange__K+: int64
environment__exchange__L-ALPHA-ALANINE: int64
environment__exchange__L-ASPARTATE: int64
environment__exchange__L-SELENOCYSTEINE: int64
environment__exchange__LEU: int64
environment__exchange__LYS: int64
environment__exchange__MAL: int64
environment__exchange__MET: int64
environment__exchange__METOH: int64
environment__exchange__MG+2: int64
environment__exchange__MI-PENTAKISPHOSPHATE: int64
environment__exchange__MN+2: int64
environment__exchange__NA+: int64
environment__exchange__NI+2: int64
environment__exchange__NITRATE: int64
environment__exchange__NITRITE: int64
environment__exchange__OXYGEN-MOLECULE: int64
environment__exchange__PHE: int64
environment__exchange__PRO: int64
environment__exchange__PROTON: int64
environment__exchange__Pi: int64
environment__exchange__S-ADENOSYL-4-METHYLTHIO-2-OXOBUTANOATE: int64
environment__exchange__S-ADENOSYLMETHIONINE: int64
environment__exchange__SER: int64
environment__exchange__SUC: int64
environment__exchange__SULFATE: int64
environment__exchange__THR: int64
environment__exchange__THYMINE: int64
environment__exchange__TRP: int64
environment__exchange__TUNGSTATE: int64
environment__exchange__TYR: int64
environment__exchange__UNDECAPRENYL-DIPHOSPHATE: int64
environment__exchange__URACIL: int64
environment__exchange__UREA: int64
environment__exchange__VAL: int64
environment__exchange__WATER: int64
environment__exchange__XANTHINE: int64
environment__exchange__ZN+2: int64
listeners__rna_counts__mRNA_counts: large_list<element: uint32>
  child 0, element: uint32
listeners__rna_counts__full_mRNA_counts: large_list<element: uint32>
  child 0, element: uint32
listeners__rna_counts__partial_mRNA_counts: large_list<element: uint32>
  child 0, element: uint32
listeners__rna_counts__mRNA_cistron_counts: large_list<element: uint32>
  child 0, element: uint32
listeners__rna_counts__full_mRNA_cistron_counts: large_list<element: uint32>
  child 0, element: uint32
listeners__rna_counts__partial_mRNA_cistron_counts: large_list<element: uint32>
  child 0, element: uint32
listeners__rna_counts__partial_rRNA_counts: large_list<element: int64>
  child 0, element: int64
listeners__rna_counts__partial_rRNA_cistron_counts: large_list<element: int64>
  child 0, element: int64
listeners__dna_supercoiling__segment_left_boundary_coordinates: large_list<element: null>
  child 0, element: null
listeners__dna_supercoiling__segment_right_boundary_coordinates: large_list<element: null>
  child 0, element: null
listeners__dna_supercoiling__segment_domain_indexes: large_list<element: null>
  child 0, element: null
listeners__dna_supercoiling__segment_superhelical_densities: large_list<element: null>
  child 0, element: null
listeners__mass__cell_mass: double
listeners__mass__water_mass: double
listeners__mass__dry_mass: double
listeners__mass__rna_mass: double
listeners__mass__rRna_mass: double
listeners__mass__tRna_mass: double
listeners__mass__mRna_mass: double
listeners__mass__dna_mass: double
listeners__mass__protein_mass: double
listeners__mass__smallMolecule_mass: double
listeners__mass__volume: double
listeners__mass__protein_mass_fraction: double
listeners__mass__rna_mass_fraction: double
listeners__mass__growth: double
listeners__mass__instantaneous_growth_rate: double
listeners__mass__dry_mass_fold_change: double
listeners__mass__protein_mass_fold_change: double
listeners__mass__rna_mass_fold_change: double
listeners__mass__small_molecule_fold_change: double
listeners__mass__projection_mass: double
listeners__mass__cytosol_mass: double
listeners__mass__extracellular_mass: double
listeners__mass__flagellum_mass: double
listeners__mass__membrane_mass: double
listeners__mass__outer_membrane_mass: double
listeners__mass__periplasm_mass: double
listeners__mass__pilus_mass: double
listeners__mass__inner_membrane_mass: double
listeners__mass__expected_mass_fold_change: double
listeners__replication_data__critical_initiation_mass: double
listeners__replication_data__critical_mass_per_oriC: double
listeners__replication_data__fork_coordinates: large_list<element: int64>
  child 0, element: int64
listeners__replication_data__fork_domains: large_list<element: int32>
  child 0, element: int32
listeners__replication_data__fork_unique_index: large_list<element: int64>
  child 0, element: int64
listeners__replication_data__number_of_oric: int64
listeners__replication_data__free_DnaA_boxes: int64
listeners__replication_data__total_DnaA_boxes: int64
listeners__rnap_data__n_total_collisions: int64
listeners__rnap_data__n_headon_collisions: int64
listeners__rnap_data__n_codirectional_collisions: int64
listeners__rnap_data__headon_collision_coordinates: large_list<element: int64>
  child 0, element: int64
listeners__rnap_data__codirectional_collision_coordinates: large_list<element: int64>
  child 0, element: int64
listeners__rnap_data__n_removed_ribosomes: int64
listeners__rnap_data__incomplete_transcription_events: large_list<element: int64>
  child 0, element: int64
listeners__rnap_data__n_empty_fork_collisions: int64
listeners__rnap_data__empty_fork_collision_coordinates: large_list<element: null>
  child 0, element: null
listeners__rnap_data__actual_elongations: int64
listeners__rnap_data__did_terminate: int64
listeners__rnap_data__termination_loss: int64
listeners__rnap_data__did_stall: int64
listeners__rnap_data__did_initialize: int64
listeners__rnap_data__rna_init_event: large_list<element: uint16>
  child 0, element: uint16
listeners__rnap_data__active_rnap_coordinates: large_list<element: int64>
  child 0, element: int64
listeners__rnap_data__active_rnap_domain_indexes: large_list<element: uint16>
  child 0, element: uint16
listeners__rnap_data__active_rnap_unique_indexes: large_list<element: int64>
  child 0, element: int64
listeners__rnap_data__active_rnap_on_stable_RNA_indexes: large_list<element: int64>
  child 0, element: int64
listeners__rnap_data__active_rnap_n_bound_ribosomes: large_list<element: uint16>
  child 0, element: uint16
listeners__rnap_data__rna_init_event_per_cistron: large_list<element: uint16>
  child 0, element: uint16
listeners__complexation_listener__complexation_events: large_list<element: uint16>
  child 0, element: uint16
listeners__equilibrium_listener__reaction_rates: large_list<element: double>
  child 0, element: double
listeners__fba_results__media_id: large_string
listeners__fba_results__conc_updates: large_list<element: double>
  child 0, element: double
listeners__fba_results__catalyst_counts: large_list<element: uint32>
  child 0, element: uint32
listeners__fba_results__translation_gtp: double
listeners__fba_results__coefficient: double
listeners__fba_results__unconstrained_molecules: large_list<element: bool>
  child 0, element: bool
listeners__fba_results__constrained_molecules: large_list<element: bool>
  child 0, element: bool
listeners__fba_results__uptake_constraints: large_list<element: double>
  child 0, element: double
listeners__fba_results__delta_metabolites: large_list<element: int64>
  child 0, element: int64
listeners__fba_results__reaction_fluxes: large_list<element: double>
  child 0, element: double
listeners__fba_results__external_exchange_fluxes: large_list<element: double>
  child 0, element: double
listeners__fba_results__objective_value: double
listeners__fba_results__shadow_prices: large_list<element: double>
  child 0, element: double
listeners__fba_results__reduced_costs: large_list<element: double>
  child 0, element: double
listeners__fba_results__target_concentrations: large_list<element: double>
  child 0, element: double
listeners__fba_results__homeostatic_objective_values: large_list<element: double>
  child 0, element: double
listeners__fba_results__kinetic_objective_values: large_list<element: double>
  child 0, element: double
listeners__fba_results__base_reaction_fluxes: large_list<element: double>
  child 0, element: double
listeners__fba_results__estimated_homeostatic_dmdt: large_list<element: int64>
  child 0, element: int64
listeners__fba_results__target_homeostatic_dmdt: large_list<element: int64>
  child 0, element: int64
listeners__fba_results__homeostatic_metabolite_counts: large_list<element: int64>
  child 0, element: int64
listeners__enzyme_kinetics__metabolite_counts_init: large_list<element: int64>
  child 0, element: int64
listeners__enzyme_kinetics__metabolite_counts_final: large_list<element: int64>
  child 0, element: int64
listeners__enzyme_kinetics__enzyme_counts_init: large_list<element: int64>
  child 0, element: int64
listeners__enzyme_kinetics__counts_to_molar: double
listeners__enzyme_kinetics__actual_fluxes: large_list<element: double>
  child 0, element: double
listeners__enzyme_kinetics__target_fluxes: large_list<element: double>
  child 0, element: double
listeners__enzyme_kinetics__target_fluxes_upper: large_list<element: double>
  child 0, element: double
listeners__enzyme_kinetics__target_fluxes_lower: large_list<element: double>
  child 0, element: double
listeners__enzyme_kinetics__target_aa_conc: large_list<element: double>
  child 0, element: double
listeners__growth_limits__fraction_trna_charged: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_allocated: large_list<element: int64>
  child 0, element: int64
listeners__growth_limits__aa_pool_size: large_list<element: int64>
  child 0, element: int64
listeners__growth_limits__aa_request_size: large_list<element: double>
  child 0, element: double
listeners__growth_limits__active_ribosome_allocated: int64
listeners__growth_limits__net_charged: large_list<element: int64>
  child 0, element: int64
listeners__growth_limits__aas_used: large_list<element: int64>
  child 0, element: int64
listeners__growth_limits__aa_count_diff: large_list<element: double>
  child 0, element: double
listeners__growth_limits__original_aa_supply: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_in_media: large_list<element: bool>
  child 0, element: bool
listeners__growth_limits__synthetase_conc: large_list<element: double>
  child 0, element: double
listeners__growth_limits__uncharged_trna_conc: large_list<element: double>
  child 0, element: double
listeners__growth_limits__charged_trna_conc: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_conc: large_list<element: double>
  child 0, element: double
listeners__growth_limits__ribosome_conc: double
listeners__growth_limits__fraction_aa_to_elongate: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_supply: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_synthesis: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_import: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_export: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_importers: large_list<element: int64>
  child 0, element: int64
listeners__growth_limits__aa_exporters: large_list<element: int64>
  child 0, element: int64
listeners__growth_limits__aa_supply_enzymes_fwd: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_supply_enzymes_rev: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_supply_aa_conc: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_supply_fraction_fwd: large_list<element: double>
  child 0, element: double
listeners__growth_limits__aa_supply_fraction_rev: large_list<element: double>
  child 0, element: double
listeners__growth_limits__ppgpp_conc: double
listeners__growth_limits__rela_conc: double
listeners__growth_limits__spot_conc: double
listeners__growth_limits__rela_syn: large_list<element: double>
  child 0, element: double
listeners__growth_limits__spot_syn: double
listeners__growth_limits__spot_deg: double
listeners__growth_limits__spot_deg_inhibited: large_list<element: double>
  child 0, element: double
listeners__growth_limits__trna_charged: large_list<element: int64>
  child 0, element: int64
listeners__growth_limits__ntp_used: large_list<element: int64>
  child 0, element: int64
listeners__growth_limits__ntp_pool_size: large_list<element: int64>
  child 0, element: int64
listeners__growth_limits__ntp_request_size: large_list<element: int64>
  child 0, element: int64
listeners__growth_limits__ntp_allocated: large_list<element: int64>
  child 0, element: int64
listeners__ribosome_data__translation_supply: large_list<element: double>
  child 0, element: double
listeners__ribosome_data__effective_elongation_rate: double
listeners__ribosome_data__aa_count_in_sequence: large_list<element: int64>
  child 0, element: int64
listeners__ribosome_data__aa_counts: large_list<element: double>
  child 0, element: double
listeners__ribosome_data__actual_elongations: int64
listeners__ribosome_data__actual_elongation_hist: large_list<element: int64>
  child 0, element: int64
listeners__ribosome_data__elongations_non_terminating_hist: large_list<element: int64>
  child 0, element: int64
listeners__ribosome_data__did_terminate: int64
listeners__ribosome_data__termination_loss: int64
listeners__ribosome_data__num_trpA_terminated: int64
listeners__ribosome_data__process_elongation_rate: double
listeners__ribosome_data__did_initialize: int64
listeners__ribosome_data__target_prob_translation_per_transcript: large_list<element: double>
  child 0, element: double
listeners__ribosome_data__actual_prob_translation_per_transcript: large_list<element: double>
  child 0, element: double
listeners__ribosome_data__mRNA_is_overcrowded: large_list<element: bool>
  child 0, element: bool
listeners__ribosome_data__ribosome_init_event_per_monomer: large_list<element: uint32>
  child 0, element: uint32
listeners__ribosome_data__max_p: double
listeners__ribosome_data__max_p_per_protein: large_list<element: double>
  child 0, element: double
listeners__ribosome_data__rRNA_initiated_TU: large_list<element: int64>
  child 0, element: int64
listeners__ribosome_data__rRNA_init_prob_TU: large_list<element: double>
  child 0, element: double
listeners__ribosome_data__total_rna_init: int64
listeners__ribosome_data__n_ribosomes_per_transcript: large_list<element: uint32>
  child 0, element: uint32
listeners__ribosome_data__n_ribosomes_on_partial_mRNA_per_transcript: large_list<element: uint32>
  child 0, element: uint32
listeners__ribosome_data__total_rRNA_initiated: int64
listeners__ribosome_data__total_rRNA_init_prob: double
listeners__ribosome_data__rRNA5S_initiated: int64
listeners__ribosome_data__rRNA16S_initiated: int64
listeners__ribosome_data__rRNA23S_initiated: int64
listeners__ribosome_data__rRNA5S_init_prob: double
listeners__ribosome_data__rRNA16S_init_prob: double
listeners__ribosome_data__rRNA23S_init_prob: double
listeners__ribosome_data__mRNA_TU_index: large_list<element: uint16>
  child 0, element: uint16
listeners__ribosome_data__n_ribosomes_on_each_mRNA: large_list<element: uint16>
  child 0, element: uint16
listeners__ribosome_data__protein_mass_on_polysomes: large_list<element: double>
  child 0, element: double
listeners__rna_degradation_listener__fraction_active_endornases: double
listeners__rna_degradation_listener__diff_relative_first_order_decay: double
listeners__rna_degradation_listener__fract_endo_rrna_counts: double
listeners__rna_degradation_listener__count_rna_degraded: large_list<element: uint16>
  child 0, element: uint16
listeners__rna_degradation_listener__count_RNA_degraded_per_cistron: large_list<element: uint16>
  child 0, element: uint16
listeners__rna_degradation_listener__nucleotides_from_degradation: int64
listeners__rna_degradation_listener__fragment_bases_digested: int64
listeners__rna_maturation_listener__total_maturation_events: int64
listeners__rna_maturation_listener__total_degraded_ntps: int64
listeners__rna_maturation_listener__unprocessed_rnas_consumed: large_list<element: int64>
  child 0, element: int64
listeners__rna_maturation_listener__mature_rnas_generated: large_list<element: int64>
  child 0, element: int64
listeners__rna_maturation_listener__maturation_enzyme_counts: large_list<element: int64>
  child 0, element: int64
listeners__rna_synth_prob__p_promoter_bound: large_list<element: double>
  child 0, element: double
listeners__rna_synth_prob__n_promoter_bound: large_list<element: int64>
  child 0, element: int64
listeners__rna_synth_prob__n_actual_bound: large_list<element: int64>
  child 0, element: int64
listeners__rna_synth_prob__n_available_promoters: large_list<element: int64>
  child 0, element: int64
listeners__rna_synth_prob__n_bound_TF_per_TU: large_list<element: large_list<element: uint16>>
  child 0, element: large_list<element: uint16>
      child 0, element: uint16
listeners__rna_synth_prob__target_rna_synth_prob: large_list<element: double>
  child 0, element: double
listeners__rna_synth_prob__actual_rna_synth_prob: large_list<element: double>
  child 0, element: double
listeners__rna_synth_prob__tu_is_overcrowded: large_list<element: bool>
  child 0, element: bool
listeners__rna_synth_prob__total_rna_init: int64
listeners__rna_synth_prob__max_p: double
listeners__rna_synth_prob__promoter_copy_number: large_list<element: uint16>
  child 0, element: uint16
listeners__rna_synth_prob__gene_copy_number: large_list<element: uint16>
  child 0, element: uint16
listeners__rna_synth_prob__bound_TF_indexes: large_list<element: uint16>
  child 0, element: uint16
listeners__rna_synth_prob__bound_TF_coordinates: large_list<element: int64>
  child 0, element: int64
listeners__rna_synth_prob__bound_TF_domains: large_list<element: uint16>
  child 0, element: uint16

,bulk,environment__exchange__4FE-4S,environment__exchange__5-Deoxy-D-Ribofuranose,environment__exchange__ACET,environment__exchange__AMMONIUM,environment__exchange__ARABINOSE,environment__exchange__ARG,environment__exchange__ASN,environment__exchange__BETAINE,environment__exchange__BUTANAL,...,boundary__length,boundary__outer_surface_area,boundary__inner_surface_area,boundary__mmol_to_counts,boundary__mass,boundary__location,boundary__angle,boundary__thrust,boundary__torque,time
0,"[0, 0, 247, 0, 0, 0, 0, 0, 0, 0, 0, 35, 1, 0, ...",0,449983,0,-3556143400,0,0,0,0,0,...,!units[2.902185899379881 micrometer],!units[9.117485900843722 micrometer ** 2],!units[7.857211164261726 micrometer ** 2],!units[1215010.3103840766 / millimolar],!units[2219.329296152958 femtogram],"[!units[25.482413973984873 micrometer], !units...",2.356642,0.0,0.0,5471.0
1,"[0, 0, 247, 0, 0, 0, 0, 0, 0, 0, 0, 35, 1, 0, ...",0,450067,0,-3556925269,0,0,0,0,0,...,!units[2.9027037435469425 micrometer],!units[9.119112756274665 micrometer ** 2],!units[7.858613145772163 micrometer ** 2],!units[1215255.2391941096 / millimolar],!units[2219.7766813964677 femtogram],"[!units[25.483323054264606 micrometer], !units...",2.355036,0.0,0.0,5472.0
2,"[0, 0, 247, 0, 0, 0, 0, 0, 0, 0, 0, 35, 1, 0, ...",0,450157,0,-3557712331,0,0,0,0,0,...,!units[2.903230100953602 micrometer],!units[9.12076635683659 micrometer ** 2],!units[7.86003817553779 micrometer ** 2],!units[1215504.1945777275 / millimolar],!units[2220.231421550997 femtogram],"[!units[25.485715609774534 micrometer], !units...",2.354519,0.0,0.0,5473.0

## Debug emit_step passing

**Debug 1**

Findings so far:

- `configs/colony_baseline_test3.json` does set `"emit_step": 60`, while `configs/colony_baseline_test.json` does not set it at all.
- `ecoli/experiments/ecoli_engine_process.py` forwards that value directly into the outer Vivarium engine with `emit_step=config.get("emit_step", 1)`.
- `ecoli/processes/engine_process.py` does not read `emit_step` itself. It only creates the inner simulation and later creates the inner emitter from `inner_emitter`.
- The run layout is the real difference: `baseline_test1` has parquet files under the outer `history/` tree, while `baseline_test3` has an empty outer `history/` tree and only the `__inner/history/` parquet snapshots.
- The sample `.pq` files are per-snapshot parquet tables whose rows still advance by 1 second inside each file. The snapshot filenames are the emitted checkpoints, so `emit_step` does not change the row-level `time` column inside a snapshot.

Debug process used:

1. Searched the codebase for `emit_step` and found only the outer engine handoff in `ecoli/experiments/ecoli_engine_process.py` plus unrelated lysis defaults.
2. Compared the two config files and confirmed `emit_step` is the only relevant config change besides seed.
3. Checked the run directories directly. `baseline_test1/history/` contains parquet files; `baseline_test3/history/` exists but has no files.
4. Verified both runs still write inner parquet snapshots under `__inner/history/`.

Current hypothesis:

- `emit_step` is being passed into the outer engine correctly.
- The remaining problem is likely in outer emitter finalization / outer history writing for the test3 run, not in the config handoff itself.

Next code to inspect:

- `ecoli/library/parquet_emitter.py` for the emit/finalize path and any condition that could suppress outer `history/` writes.
- `ecoli/experiments/ecoli_engine_process.py` around the outer engine teardown path, especially where `emitter.success = True` and `finalize()` are called.

**Debug 2**

Findings so far:

- `emit_step` is present in `configs/colony_baseline_test3.json` and absent from `configs/colony_baseline_test.json`.
- `ecoli/experiments/ecoli_engine_process.py` forwards it into the outer Vivarium engine with `emit_step=config.get("emit_step", 1)`.
- `ecoli/processes/engine_process.py` does not read `emit_step`; it only creates the inner simulation and the inner emitter.
- `ecoli/library/parquet_emitter.py` writes outer parquet files in batches of 400 emits by default (`batch_size=400`) and only flushes the remainder in `finalize()`.
- The outer history tree matches that behavior: test1 has 15 files under `history/`, while test3 has 0 files under the same outer `history/` tree.
- Both runs still have inner per-timestep parquet snapshots under `__inner/history/`.

What that suggests:

- The 60-second setting is not being dropped at the config-to-engine handoff.
- The `emit_step=60` run only produces about 100 outer emits over 6000 s, so it never reaches the default batch flush threshold of 400 during the run.
- If the outer emitter is **not finalized** cleanly at shutdown, the buffered outer data will never be written, which explains why test3 has no outer `history/` files even though the inner run does.
- This also explains why the first record can look the same: the parquet rows are still snapshot rows, and the files are organized by batch index, not by the 60-second emit cadence itself.

Potential fix:

- Explicitly flush the outer ParquetEmitter at the end of `colony_save_states()` or immediately before returning from `run_simulation()`, instead of relying on the implicit shutdown path.
- The safest version would be to set `engine.emitter.success = True` and call `engine.emitter.finalize()` after the final `engine.update(...)` has completed.
- If the intent is to get a physical file every 60 seconds, then `batch_size` also needs to be reconsidered, because the default `400` batches emits together even when the logical emit cadence is 60 s.

Debug steps completed:

1. Searched for `emit_step` and found only the outer engine handoff plus unrelated lysis defaults.
2. Compared the two colony configs and confirmed `emit_step: 60` is the only relevant config difference besides seed.
3. Checked the run trees directly.
4. Counted outer history files: test1 has 15, test3 has 0.
5. Verified both runs still write per-timestep parquet snapshots under `__inner/history/`.
6. Confirmed the outer ParquetEmitter buffers writes in batches of 400 and only flushes leftovers in `finalize()`.

Next code to inspect:

- The outer shutdown/finalization path that should flush the parquet emitter after `colony_save_states()` / `engine.end()`.
- Whether `colony_save_states()` should explicitly finalize the outer emitter when using parquet output.

## Fix2

"Outer Parquet Emitter Shutdown Flush"

### Changes to `ecoli/experiments/ecoli_engine_process.py`

In the normal shutdown path of `run_simulation()`:

* After `engine.end()`, mark the outer Parquet emitter as successful.
* Explicitly call `engine.emitter.finalize()` so that buffered Parquet output is flushed and written when the simulation ends.
* This ensures that short runs that do not reach the emitter's normal batch threshold still produce the expected outer Parquet history files.

### Verification

The fix was verified by running `baseline_test4`.

The resulting **outer Parquet folder saves data at the configured 60-second `emit_step`**, with only three output points:

```text
0 s
60 s
120 s
```

This confirms that the outer Parquet emitter is correctly emitting at the configured cadence and that its buffered data is successfully written at normal shutdown.

At this stage, **no output is produced in the inner Parquet folder**. The missing inner output was subsequently identified as a separate issue related to the inner `ParquetEmitter` not being finalized on normal shutdown, which was addressed in Fix 3.

## Debug: outer/inner subfolder data emission

```bash
python ecoli/experiments/ecoli_engine_process.py --config configs/colony_baseline_test4.json
```

**Debug Record**

- Compared the outputs directly:
  - `baseline_test4` has outer parquet history files and no inner parquet history files.
  - `baseline_test3` has inner parquet history files and no outer parquet history files.
- Traced the code paths:
  - The outer emitter now flushes on normal shutdown in `run_simulation()`, so short runs can write outer `history/` files even if they never reach the batch threshold.
  - The inner `ParquetEmitter` is only finalized on division or exception inside `EngineProcess.next_update()`.
- Root cause:
  - `baseline_test4` is a short run that does not divide, so the inner emitter never reaches its division-based finalize path and its buffered parquet rows stay unwritten.
- Potential fix:
  - Add a normal-shutdown finalize for inner emitters too, or finalize all active `ParquetEmitter` instances after the colony run completes, so short non-dividing runs write both outer and inner parquet output.

In [ ]:
from pathlib import Path

import pandas as pd

run_root = Path("/home/katha/dev/vEcoli-colony-sim/out/colony_runs/baseline_test4_2/2026-08-27_15-32-42_276247%2B0000__inner")
pq_file = sorted(run_root.glob("**/history/**/*.pq"))[0]
frame = pd.read_parquet(pq_file)

print(pq_file)
print(frame)

/home/katha/dev/vEcoli-colony-sim/out/colony_runs/baseline_test4_2/2026-08-27_15-32-42_276247%2B0000__inner/history/experiment_id=2026-08-27_15-32-42_276247%2B0000__inner/variant=0/lineage_seed=0/generation=1/agent_id=0/2.pq
                                                bulk  \
0  [0, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0, 33, 0, 0, ...
1  [0, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0, 33, 0, 0, ...

   environment__exchange__4FE-4S  \
0                              0
1                              0

   environment__exchange__5-Deoxy-D-Ribofuranose  environment__exchange__ACET  \
0                                              0                            0
1                                              0                            0

   environment__exchange__AMMONIUM  environment__exchange__ARABINOSE  \
0                                0                                 0
1                        -28733823                                 0

   environment__exchange__ARG  environment__exchange__ASN  \
0                           0                           0
1                           0                           0

   environment__exchange__BETAINE  environment__exchange__BUTANAL  ...  \
0                               0                               0  ...
1                               0                               0  ...

                        boundary__length  \
0  !units[1.7469161865900422 micrometer]
1  !units[1.7593566338314377 micrometer]

                boundary__outer_surface_area  \
0  !units[5.488099058228373 micrometer ** 2]
1  !units[5.527181875889312 micrometer ** 2]

                 boundary__inner_surface_area  \
0   !units[4.729500397351408 micrometer ** 2]
1  !units[4.7631809486125745 micrometer ** 2]

                 boundary__mmol_to_counts  \
0  !units[668593.3494160369 / millimolar]
1  !units[674477.4051473264 / millimolar]

                         boundary__mass  \
0  !units[1221.2479144337376 femtogram]
1  !units[1231.9956892904956 femtogram]

                                  boundary__location  boundary__angle  \
0  [!units[25.0 micrometer], !units[25.0 micromet...         0.000000
1  [!units[24.978143578710934 micrometer], !units...         0.332962

   boundary__thrust  boundary__torque  time
0               0.0               0.0   0.0
1               0.0               0.0  60.0

[2 rows x 411 columns]

## Fix3

"Inner Parquet Emitter Finalization and Emit Cadence"

### Changes to `ecoli/experiments/ecoli_engine_process.py`

Fix 3 addressed missing inner Parquet output for short, non-dividing colony simulations.

The root cause was that the inner `ParquetEmitter` was only finalized from the division/exception paths inside `EngineProcess.next_update()`. For a short run that did not divide, buffered inner Parquet rows were therefore never written, while the outer emitter was finalized normally at shutdown.

The fix makes the inner simulation follow the configured emission cadence and explicitly finalizes nested Parquet emitters when the colony simulation exits:

* Pass `emit_step` from the top-level simulation configuration into the outer `EcoliEngineProcess` configuration.
* Pass the same `emit_step` through `EcoliEngineProcess.generate_processes()` into the inner `EngineProcess`.
* Add `finalize_parquet_emitters()`, which recursively traverses nested process dictionaries and calls `finalize()` on every `ParquetEmitter`, while avoiding duplicate finalization of the same emitter.
* After `engine.end()`, mark the outer Parquet emitter as successful and finalize it.
* Then recursively finalize the inner Parquet emitters so buffered data from short, non-dividing runs is flushed to disk.

Relevant code changes are in the `EcoliEngineProcess` configuration and process construction, the new `finalize_parquet_emitters()` helper, and the normal shutdown path in `run_simulation()`.

### Verification

Fix 3 was re-tested with `baseline_test4_2`. The resulting output confirms that **both the outer and inner Parquet emitters now use the configured 60-second `emit_step`**.

For the test run, each output contains exactly three emission points:

```text
0 s
60 s
120 s
```

This confirms that the `emit_step` configuration is being passed through to the inner `EngineProcess` correctly, and that both outer and inner Parquet outputs are being emitted at the same 60-second cadence.
The test therefore verifies both parts of Fix 3: **the inner emitter receives the intended emission cadence, and its buffered output is finalized on normal shutdown.**