In [1]:
import pandas as pd
import os, dill
import numpy as np
import cvxpy as cp
from typing import Iterable, Optional, Mapping, cast
from plotly import graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px

os.chdir(os.path.expanduser('~/dev/vEcoli'))

%load_ext autoreload

In [2]:
# import sim
time = '600'
date = '2026-01-22'
experiment = 'homeostatic_only'
condition = 'basal'
entry = f'{experiment}_{time}_{date}'
folder = f'out/objective_weight/{condition}/{entry}/'

output = np.load(folder + '0_output.npy',allow_pickle='TRUE').item()
output = output['agents']['0']
fba = output['listeners']['fba_results']
bulk = pd.DataFrame(output['bulk'])
f = open(folder + 'agent_steps.pkl', 'rb')
agent = dill.load(f)
f.close()

metabolism = agent['ecoli-metabolism-redux-classic']

In [3]:
# get objective terms across time
counts_to_molar = output['listeners']['enzyme_kinetics']['counts_to_molar']

homeostatic_term = np.asarray(fba['homeostatic_term'])/counts_to_molar #change to count
# secretion_term = np.asarray(fba['secretion_term'])/counts_to_molar
# efficiency_term = np.asarray(fba['efficiency_term'])/counts_to_molar
# kinetic_term = np.asarray(fba['kinetic_term'])/counts_to_molar

time = np.arange(len(homeostatic_term))

objective_weights_sim = {
            "secretion": 0.01,
            "efficiency": 0.001,
            "kinetics": 0.005,
            "homeostatic": 1,
}

In [4]:
from plotly.colors import qualitative as q

spec_term = {
    "Homeostatic": (homeostatic_term, objective_weights_sim['homeostatic']),
    # "Secretion":   (secretion_term,   objective_weights_sim['secretion']),
    # "Efficiency":  (efficiency_term,  objective_weights_sim['efficiency']),
    # "Kinetic":     (kinetic_term,     objective_weights_sim['kinetics']),
}

spec_no_weights = {
    "Homeostatic": (homeostatic_term/objective_weights_sim['homeostatic'], objective_weights_sim['homeostatic']),
    # "Secretion":   (secretion_term/objective_weights_sim['secretion'],     objective_weights_sim['secretion']),
    # "Efficiency":  (efficiency_term/objective_weights_sim['efficiency'],   objective_weights_sim['efficiency']),
    # "Kinetic":     (kinetic_term/objective_weights_sim['kinetics'],        objective_weights_sim['kinetics']),
}


palette = q.Pastel  # consistent colors across both sets
colors = {name: palette[i % len(palette)] for i, name in enumerate(spec_term)}


fig = go.Figure()

# Add weighted (solid) + unweighted (dotted) per term
for i, (name, (y_w, w)) in enumerate(spec_term.items()):
    # solid, weighted
    fig.add_trace(go.Scatter(
        x=time, y=y_w, mode="lines",
        name=f"{name} (weighted)",
        line=dict(color=colors[name], dash="solid"),
        legendgroup=name,
        legendgrouptitle_text=name if i == 0 else None,
        hovertemplate=f"{name.lower()} weight={w}<br>{name.lower()} term value=%{{y:.4g}}<extra></extra>"
    ))
    # dotted, unweighted
    y_uw, w_uw = spec_no_weights[name]
    fig.add_trace(go.Scatter(
        x=time, y=y_uw, mode="lines",
        name=f"{name} (unweighted)",
        line=dict(color=colors[name], dash="dot"),
        legendgroup=name,
        hovertemplate=f"{name.lower()} (no weight)<br>{name.lower()} value=%{{y:.4g}}<extra></extra>"
    ))

fig.update_layout(
    title="Change of Objective Term Values (Counts) Over Sim",
    xaxis_title="Time (s)",
    yaxis=dict(title="Objective Term Value", type="log", tickformat=".0e"),
    template="plotly_white",
    colorway=px.colors.qualitative.Pastel,
    legend=dict(title="Terms", groupclick="togglegroup"),  # click once to toggle both lines in a group
    paper_bgcolor='rgba(255, 0, 0, 0)',
    plot_bgcolor='rgba(255, 0, 0, 0)',
)

# fig.show()
fig.write_image("/Users/HeenaSaqib/dev/vEcoli/notebooks/Heena notebooks/Metabolism_New Genes/out/objective_weights/home_only_sim_terms.png",     width=800, height=400, scale=3)

In [5]:
# find top 10 homeostatic loss
estimated_homeostatic_dmdt = pd.DataFrame(fba["estimated_homeostatic_dmdt"][1:], columns=metabolism.homeostatic_metabolites)
target_homeostatic_dmdt = pd.DataFrame(fba["target_homeostatic_dmdt"][1:], columns=metabolism.homeostatic_metabolites)
homeostatic_count = pd.DataFrame(np.asarray(fba["homeostatic_metabolite_counts"][1:]), columns = metabolism.homeostatic_metabolites)

# calculate individual metabolite objective loss
homeostatic_objective  = np.abs(target_homeostatic_dmdt - estimated_homeostatic_dmdt)/homeostatic_count

# find top 10 metabolites with most lost over time
met_loss_avg = homeostatic_objective.mean(axis=0)
time_loss_avg = homeostatic_objective.mean(axis=1)

temp = homeostatic_objective[time_loss_avg > 0]
temp = temp.loc[:, met_loss_avg > 0]
temp

     CPD-12261[p]  glycogen-monomer[c]
0        0.000000         4.923154e-08
62       0.000269         0.000000e+00
63       0.000533         0.000000e+00
64       0.000796         0.000000e+00
65       0.001054         0.000000e+00
..            ...                  ...
595      0.014069         0.000000e+00
596      0.014347         0.000000e+00
597      0.014625         0.000000e+00
598      0.014903         0.000000e+00
599      0.015180         0.000000e+00

[132 rows x 2 columns]

In [6]:
def get_subset_S(S, met_of_interest):
    S_met = S.loc[met_of_interest, :]
    S_met = S_met.loc[:,~np.all(S_met == 0, axis=0)]
    return S_met, S_met.columns

In [7]:
stoichiometry = metabolism.stoichiometry.copy()
reaction_names = metabolism.reaction_names
metabolites = metabolism.metabolite_names.copy()
S = stoichiometry .copy()
S = pd.DataFrame(S, index=metabolites, columns=reaction_names)


S_met, rxns =  get_subset_S(S, temp.columns)
S_met

                     RXN-11302  glycogen-monomer-extension
CPD-12261[p]                 1                           0
glycogen-monomer[c]          0                           1

## These metabolites are both manually added for murein (CPD-12261) and glycogen. It's odd to see that flow can be sustained through these metabolites at some time steps but the need is n't met for some other timestep, even when homeosatic objective is the only objective present.

In [8]:
###----- 1. Visualize metabolite exchange -----###
met_of_interest = ["CPD-12261[p]", "glycogen-monomer[c]"]

dmdt_diff = (target_homeostatic_dmdt - estimated_homeostatic_dmdt)/homeostatic_count
dmdt_diff_interest = dmdt_diff.loc[:,met_of_interest]
dmdt_diff_interest

     CPD-12261[p]  glycogen-monomer[c]
0        0.000000        -4.923154e-08
1        0.000000         0.000000e+00
2        0.000000         0.000000e+00
3        0.000000         0.000000e+00
4        0.000000         0.000000e+00
..            ...                  ...
595      0.014069         0.000000e+00
596      0.014347         0.000000e+00
597      0.014625         0.000000e+00
598      0.014903         0.000000e+00
599      0.015180         0.000000e+00

[600 rows x 2 columns]

In [28]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# --- 0) Compute unmet need for all homeostatic metabolites ---
dmdt_diff = (target_homeostatic_dmdt - estimated_homeostatic_dmdt) / homeostatic_count

# Optional: drop timepoints/columns with all-NaN or zeros if needed
dmdt_diff = dmdt_diff.replace([np.inf, -np.inf], np.nan).div(counts_to_molar[1:], axis='rows')

# --- 1) Pick top 5 metabolites by "biggest unmet need" ---
# Recommended metric: mean absolute unmet need over time
met_score = dmdt_diff.abs().mean(axis=0).sort_values(ascending=False)

top5_mets = met_score.head(5).index.tolist()

# If you instead want "most negative" (largest sustained deficit), use:
# met_score = dmdt_diff.mean(axis=0).sort_values()  # most negative first
# top5_mets = met_score.head(5).index.tolist()

top5_bar = met_score.loc[top5_mets]

# --- 2) Prepare bottom plot (your metabolites of interest) ---
met_of_interest = ["CPD-12261[p]", "glycogen-monomer[c]"]
df_line = dmdt_diff.loc[:, met_of_interest].copy()
df_line.index.name = "time_s"

long = (
    df_line.reset_index()
           .melt(id_vars="time_s", var_name="metabolite", value_name="unmet_need")
)

# --- 3) Consistent pastel colors (shared across both subplots) ---
pastel = px.colors.qualitative.Pastel
all_mets_for_colors = list(dict.fromkeys(top5_mets + met_of_interest))  # preserve order, unique
color_map = {m: pastel[i % len(pastel)] for i, m in enumerate(all_mets_for_colors)}

# --- 4) Make subplots: bar on top, lines on bottom ---
fig = make_subplots(
    rows=2, cols=1,
    row_heights=[0.35, 0.65],
    vertical_spacing=0.12,
)

# Top: bar chart (histogram-like summary)
fig.add_trace(
    go.Bar(
        x=top5_bar.index,
        y=top5_bar.values,
        marker=dict(color=[color_map.get(m, pastel[0]) for m in top5_bar.index]),
        text = [f'{val:.1e}' for val in top5_bar.values],
        name="Unmet Homeostatic Need"
    ),
    row=1, col=1
)

# Bottom: time series for metabolites of interest
for met in met_of_interest:
    fig.add_trace(
        go.Scatter(
            x=long.loc[long["metabolite"] == met, "time_s"],
            y=long.loc[long["metabolite"] == met, "unmet_need"],
            mode="lines",
            name=met,
            line=dict(color=color_map.get(met, pastel[1]))
        ),
        row=2, col=1
    )


fig.update_yaxes(title_text="Unmet Need", row=1, col=1)

fig.update_xaxes(title_text="Time (s)", row=2, col=1)
fig.update_yaxes(title_text="L1_|Target - Estimate|", row=2, col=1)

fig.update_layout(
    title="Unmet homeostatic need summary + culprit metabolite need timeseries",
    xaxis_title="Time (s)",
    yaxis=dict(title="Objective Term Value", type="log", tickformat=".0e"),
    template="plotly_white",
    colorway=px.colors.qualitative.Pastel,
    barcornerradius=15,
    # paper_bgcolor='rgba(255, 0, 0, 0)',
    # plot_bgcolor='rgba(255, 0, 0, 0)',
)

# fig.show()
fig.write_image("/Users/HeenaSaqib/dev/vEcoli/notebooks/Heena notebooks/Metabolism_New Genes/out/objective_weights/homeo_only_met_need.png",
                width=900, height=600, scale=3)

### glycogen-monomer[c] was made too much at timestep 1 (because diff is negative --> estimate > target). CPD-12261[p] is the main culprit for unmet need

In [29]:
###----- 2. Check if any of the reactions upstream of these metabolites have no enzyme, causing zero flow-----###
# 2.1 Run parsimonious FBA (pFBA) with to maximize CPD-12261 export to extract path of making CPD-12261
import cvxpy as cp
v = cp.Variable(len(reaction_names), nonneg=True)
e = cp.Variable(metabolism.network_flow_model.n_exch_rxns, nonneg=True)
dm = metabolism.network_flow_model.S_orig @ v + metabolism.network_flow_model.S_exch @ e
exch = metabolism.network_flow_model.S_exch @ e
upper_flux_bound = 100

constr = []
constr.append(dm[metabolism.network_flow_model.intermediates_idx] == 0)
constr.extend([v >= 0, v <= upper_flux_bound, e >= 0, e <= upper_flux_bound])
constr.extend([cp.sum(v) >= 10 ])

# objective is to maximize dm[index_CPD-12261[p]] and minimize total flux
CPD_12261_index = metabolites.index('CPD-12261[p]')
objective = -dm[CPD_12261_index] + cp.sum(v)

problem = cp.Problem(cp.Minimize(objective), constr)
problem.solve(solver=cp.GLOP)

np.float64(9.805825242718447)

In [30]:
solution = pd.DataFrame(v.value, index=reaction_names)
homeostatic_metabolite_idx = [metabolites.index(met) for met in metabolism.homeostatic_metabolites]
dm_solution = pd.DataFrame(dm[homeostatic_metabolite_idx].value, index=metabolism.homeostatic_metabolites)
reactions_making_CPD12261 = solution.loc[solution[0] != 0].index

reaction_catalyst_counts_all_time = pd.DataFrame(fba['reaction_catalyst_counts'][1:], columns=reaction_names)
reaction_catalyst_counts_CPD12261 = reaction_catalyst_counts_all_time.loc[:, reactions_making_CPD12261]

In [31]:
# UDP-NACMURALA-GLU-LIG-RXN is the only reaction with occasional zero enzyme counts
# 2.2 Check to see if zero enzyme counts of UDP-NACMURALA-GLU-LIG-RXN coincides with that of unmet CPD-12261 need
# enzyme is UDP-NACMURALA-GLU-LIG-MONOMER
reaction = 'UDP-NACMURALA-GLU-LIG-RXN'
enzyme_timeseries = reaction_catalyst_counts_CPD12261.loc[:, reaction]
enzyme_name = metabolism.parameters['reaction_catalysts'][reaction]

In [40]:
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

met = "CPD-12261[p]"  # (you wrote CPD-12251[p] once—use the exact column name you have)
enzyme_label = f"{enzyme_name} (counts)"
need_label = f"{met} unmet need (normalized dmdt diff)"

# --- align indices (time) robustly ---
enz = enzyme_timeseries.copy()
need = dmdt_diff_interest[met].copy() if isinstance(dmdt_diff_interest, pd.DataFrame) else dmdt_diff_interest
pastel = px.colors.qualitative.Pastel
# Ensure both are Series with numeric index
enz = pd.Series(enz.values, index=enz.index, name="enzyme_counts")
need = pd.Series(need.values, index=need.index, name="unmet_need")

# Inner-join on shared timepoints
df_plot = pd.concat([enz, need], axis=1, join="inner").dropna()

fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(
    go.Scatter(
        x=df_plot.index,
        y=df_plot["enzyme_counts"],
        mode="lines",
        name=enzyme_label,
    ),
    secondary_y=False
)

fig.add_trace(
    go.Scatter(
        x=df_plot.index,
        y=df_plot["unmet_need"],
        mode="lines",
        name=need_label,
    ),
    secondary_y=True
)

fig.update_layout(
    title=f"Enzyme availability of UDP-NACMURALA-GLU-LIG-RXN vs unmet need for {met}",
    template="plotly_white",
    legend_title_text="Trace",
    colorway=px.colors.qualitative.Pastel,
    paper_bgcolor='rgba(255, 0, 0, 0)',
    plot_bgcolor='rgba(255, 0, 0, 0)',
)

fig.update_xaxes(title_text="Time (s)")
fig.update_yaxes(title_text="Enzyme counts", secondary_y=False)
fig.update_yaxes(title_text="L1_|Target - Estimate|", secondary_y=True)

# fig.show()
fig.write_image("/Users/HeenaSaqib/dev/vEcoli/notebooks/Heena notebooks/Metabolism_New Genes/out/objective_weights/enzyme_availiability_vs_unmet_need.png",
                width=1400, height=500, scale=3)

# Scratch

In [ ]:
v = cp.Variable(len(reaction_names), nonneg=True)
e = cp.Variable(metabolism.network_flow_model.n_exch_rxns, nonneg=True)
dm = metabolism.network_flow_model.S_orig @ v + metabolism.network_flow_model.S_exch @ e
exch = metabolism.network_flow_model.S_exch @ e
upper_flux_bound = 100

constr = []
constr.append(dm[metabolism.network_flow_model.intermediates_idx] == 0)
constr.extend([v >= 0, v <= upper_flux_bound, e >= 0, e <= upper_flux_bound])

# objective is to maximize dm[index_CPD-12261[p]] and minimize total flux
CPD_12261_index = metabolites.index('CPD-12261[p]')
# objective = cp.sum(v
#
# problem = cp.Problem(cp.Minimize(objective), constr)
# problem.solve(solver=cp.GLOP)

In [48]:
reactions_making_CPD12261

Index(['DIAMINOPIMEPIM-RXN', 'GLUTRACE-RXN', 'NACGLCTRANS-RXN',
       'NADH-DEHYDROG-A-RXN-NADH/UBIQUINONE-8/PROTON//NAD/CPD-9956/PROTON.46.',
       'PHOSNACMURPENTATRANS-RXN', 'RXN-11302',
       'RXN0-5268-CPD-9956/OXYGEN-MOLECULE/PROTON//UBIQUINONE-8/WATER/PROTON.59.',
       'RXN0-5405', 'TRANS-RXN0-286', 'TRANS-RXN0-474',
       'UDP-NACMUR-ALA-LIG-RXN', 'UDP-NACMURALA-GLU-LIG-RXN',
       'UDP-NACMURALGLDAPAALIG-RXN', 'UDP-NACMURALGLDAPLIG-RXN',
       'UDPNACETYLGLUCOSAMENOLPYRTRANS-RXN',
       'UDPNACETYLMURAMATEDEHYDROG-RXN (reverse)',
       'UNDECAPRENYL-DIPHOSPHATASE-RXN[CCO-CYTOSOL]-UNDECAPRENYL-DIPHOSPHATE/WATER//CPD-9646/Pi/PROTON.64.'],
      dtype='object')

In [44]:
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6]])
scaler = StandardScaler()
normalized_data = scaler.fit_transform(data)

9403